# Clustering on boston housing data

In [7]:
pd.read_csv?

In [41]:
import pandas as pd
df = pd.read_csv('../Boston housing project/housing.data',delim_whitespace=True,header=None)
col_names = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']
df.columns = col_names
X = df.loc[:,df.columns!='MEDV']
col_X = X.columns 
y = df['MEDV'].values
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [42]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import itertools
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestRegressor
from mlxtend.classifier import EnsembleVoteClassifier
from mlxtend.plotting import plot_decision_regions

# Initializing Classifiers
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=9)
kmeans.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=9, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [47]:
y_kmeans = kmeans.predict(X)
for i in y_kmeans:
    print(i)

0
5
5
5
5
5
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
6
0
6
0
0
0
0
8
8
5
5
5
5
5
5
5
5
5
5
5
8
8
3
8
7
8
8
0
0
0
0
0
5
7
7
7
7
7
0
0
0
0
7
3
3
3
3
3
8
0
8
0
5
5
5
5
0
0
0
0
0
8
0
0
0
0
0
0
3
3
6
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
5
5
5
5
5
5
5
3
3
3
3
3
3
3
6
3
3
3
3
3
3
3
3
3
3
6
6
3
3
3
3
3
3
6
3
6
6
3
3
3
3
3
3
3
3
6
3
6
3
3
3
3
0
0
0
0
0
0
0
5
5
5
5
5
5
5
5
7
7
7
7
7
7
8
8
8
7
7
7
7
7
7
7
8
8
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
8
0
0
0
0
8
0
0
7
0
7
7
7
7
7
7
7
7
8
0
0
0
0
0
0
0
0
0
0
0
0
5
5
5
5
5
8
8
8
8
8
5
5
5
5
8
8
8
8
8
8
8
8
8
8
0
0
0
0
0
7
7
7
7
7
7
5
5
5
5
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
3
3
3
8
8
5
5
5
5
5
5
5
5
0
3
7
7
7
7
7
8
7
7
7
7
8
7
7
4
4
4
4
4
4
4
4
4
4
1
2
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
1
4
4
4
4
4
4
4
4
4
4
4
4
4
4
1
4
4
4
4
1
4
4
1
1
1
2
2
2
1
2
2
2
2
2
2
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
4
4
4
4
4
1
2
1
4
4
1
2
4
4
4
2
2
2
2
1
4
1
4
4
4
4
1
2
1
4
4
4
4
4
4
4
1
4
4
4
4
4
4
4
4
4
4
4
4
4
1
1
4
4
3
3
3
3
3
3
3
3
0
0
0
0
0

In [56]:
# in row_dict we store actual meanings of rows, in my case it's russian words
clusters = {}
n = 0
for item in y_kmeans:
    if item in clusters:
        clusters[item].append(X.iloc[n,:])
    else:
        clusters[item] = [X.iloc[n,:]]
    n +=1
for item in clusters:
    print ("Cluster ", item)
    for i in clusters[item]:
        print(i)

Cluster  0
CRIM         0.00632
ZN          18.00000
INDUS        2.31000
CHAS         0.00000
NOX          0.53800
RM           6.57500
AGE         65.20000
DIS          4.09000
RAD          1.00000
TAX        296.00000
PTRATIO     15.30000
B          396.90000
LSTAT        4.98000
Name: 0, dtype: float64
CRIM         0.08829
ZN          12.50000
INDUS        7.87000
CHAS         0.00000
NOX          0.52400
RM           6.01200
AGE         66.60000
DIS          5.56050
RAD          5.00000
TAX        311.00000
PTRATIO     15.20000
B          395.60000
LSTAT       12.43000
Name: 6, dtype: float64
CRIM         0.14455
ZN          12.50000
INDUS        7.87000
CHAS         0.00000
NOX          0.52400
RM           6.17200
AGE         96.10000
DIS          5.95050
RAD          5.00000
TAX        311.00000
PTRATIO     15.20000
B          396.90000
LSTAT       19.15000
Name: 7, dtype: float64
CRIM         0.21124
ZN          12.50000
INDUS        7.87000
CHAS         0.00000
NOX          0.52400
RM           5.63100
AGE        100.00000
DIS          6.08210
RAD          5.00000
TAX        311.00000
PTRATIO     15.20000
B          386.63000
LSTAT       29.93000
Name: 8, dtype: float64
CRIM         0.17004
ZN          12.50000
INDUS        7.87000
CHAS         0.00000
NOX          0.52400
RM           6.00400
AGE         85.90000
DIS          6.59210
RAD          5.00000
TAX        311.00000
PTRATIO     15.20000
B          386.71000
LSTAT       17.10000
Name: 9, dtype: float64
CRIM         0.22489
ZN          12.50000
INDUS        7.87000
CHAS         0.00000
NOX          0.52400
RM           6.37700
AGE         94.30000
DIS          6.34670
RAD          5.00000
TAX        311.00000
PTRATIO     15.20000
B          392.52000
LSTAT       20.45000
Name: 10, dtype: float64
CRIM         0.11747
ZN          12.50000
INDUS        7.87000
CHAS         0.00000
NOX          0.52400
RM           6.00900
AGE         82.90000
DIS          6.22670
RAD          5.00000
TAX        311.00000
PTRATIO     15.20000
B          396.90000
LSTAT       13.27000
Name: 11, dtype: float64
CRIM         0.09378
ZN          12.50000
INDUS        7.87000
CHAS         0.00000
NOX          0.52400
RM           5.88900
AGE         39.00000
DIS          5.45090
RAD          5.00000
TAX        311.00000
PTRATIO     15.20000
B          390.50000
LSTAT       15.71000
Name: 12, dtype: float64
CRIM         0.62976
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.94900
AGE         61.80000
DIS          4.70750
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          396.90000
LSTAT        8.26000
Name: 13, dtype: float64
CRIM         0.63796
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           6.09600
AGE         84.50000
DIS          4.46190
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          380.02000
LSTAT       10.26000
Name: 14, dtype: float64
CRIM         0.62739
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.83400
AGE         56.50000
DIS          4.49860
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          395.62000
LSTAT        8.47000
Name: 15, dtype: float64
CRIM         1.05393
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.93500
AGE         29.30000
DIS          4.49860
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          386.85000
LSTAT        6.58000
Name: 16, dtype: float64
CRIM         0.7842
ZN           0.0000
INDUS        8.1400
CHAS         0.0000
NOX          0.5380
RM           5.9900
AGE         81.7000
DIS          4.2579
RAD          4.0000
TAX        307.0000
PTRATIO     21.0000
B          386.7500
LSTAT       14.6700
Name: 17, dtype: float64
CRIM         0.80271
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.45600
AGE         36.60000
DIS          3.79650
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          288.99000
LSTAT       11.69000
Name: 18, dtype: float64
CRIM         0.7258
ZN           0.0000
INDUS        8.1400
CHAS         0.0000
NOX          0.5380
RM           5.7270
AGE         69.5000
DIS          3.7965
RAD          4.0000
TAX        307.0000
PTRATIO     21.0000
B          390.9500
LSTAT       11.2800
Name: 19, dtype: float64
CRIM         1.25179
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.57000
AGE         98.10000
DIS          3.79790
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          376.57000
LSTAT       21.02000
Name: 20, dtype: float64
CRIM         0.85204
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.96500
AGE         89.20000
DIS          4.01230
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          392.53000
LSTAT       13.83000
Name: 21, dtype: float64
CRIM         1.23247
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           6.14200
AGE         91.70000
DIS          3.97690
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          396.90000
LSTAT       18.72000
Name: 22, dtype: float64
CRIM         0.98843
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.81300
AGE        100.00000
DIS          4.09520
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          394.54000
LSTAT       19.88000
Name: 23, dtype: float64
CRIM         0.75026
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.92400
AGE         94.10000
DIS          4.39960
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          394.33000
LSTAT       16.30000
Name: 24, dtype: float64
CRIM         0.84054
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.59900
AGE         85.70000
DIS          4.45460
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          303.42000
LSTAT       16.51000
Name: 25, dtype: float64
CRIM         0.67191
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.81300
AGE         90.30000
DIS          4.68200
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          376.88000
LSTAT       14.81000
Name: 26, dtype: float64
CRIM         0.95577
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           6.04700
AGE         88.80000
DIS          4.45340
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          306.38000
LSTAT       17.28000
Name: 27, dtype: float64
CRIM         0.77299
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           6.49500
AGE         94.40000
DIS          4.45470
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          387.94000
LSTAT       12.80000
Name: 28, dtype: float64
CRIM         1.00245
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           6.67400
AGE         87.30000
DIS          4.23900
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          380.23000
LSTAT       11.98000
Name: 29, dtype: float64
CRIM         1.13081
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.71300
AGE         94.10000
DIS          4.23300
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          360.17000
LSTAT       22.60000
Name: 30, dtype: float64
CRIM         1.35472
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           6.07200
AGE        100.00000
DIS          4.17500
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          376.73000
LSTAT       13.04000
Name: 31, dtype: float64
CRIM         1.15172
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.70100
AGE         95.00000
DIS          3.78720
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          358.77000
LSTAT       18.35000
Name: 33, dtype: float64
CRIM         0.06417
ZN           0.00000
INDUS        5.96000
CHAS         0.00000
NOX          0.49900
RM           5.93300
AGE         68.20000
DIS          3.36030
RAD          5.00000
TAX        279.00000
PTRATIO     19.20000
B          396.90000
LSTAT        9.68000
Name: 35, dtype: float64
CRIM         0.09744
ZN           0.00000
INDUS        5.96000
CHAS         0.00000
NOX          0.49900
RM           5.84100
AGE         61.40000
DIS          3.37790
RAD          5.00000
TAX        279.00000
PTRATIO     19.20000
B          377.56000
LSTAT       11.41000
Name: 36, dtype: float64
CRIM         0.08014
ZN           0.00000
INDUS        5.96000
CHAS         0.00000
NOX          0.49900
RM           5.85000
AGE         41.50000
DIS          3.93420
RAD          5.00000
TAX        279.00000
PTRATIO     19.20000
B          396.90000
LSTAT        8.77000
Name: 37, dtype: float64
CRIM         0.17505
ZN           0.00000
INDUS        5.96000
CHAS         0.00000
NOX          0.49900
RM           5.96600
AGE         30.20000
DIS          3.84730
RAD          5.00000
TAX        279.00000
PTRATIO     19.20000
B          393.43000
LSTAT       10.13000
Name: 38, dtype: float64
CRIM         0.10328
ZN          25.00000
INDUS        5.13000
CHAS         0.00000
NOX          0.45300
RM           5.92700
AGE         47.20000
DIS          6.93200
RAD          8.00000
TAX        284.00000
PTRATIO     19.70000
B          396.90000
LSTAT        9.22000
Name: 59, dtype: float64
CRIM         0.14932
ZN          25.00000
INDUS        5.13000
CHAS         0.00000
NOX          0.45300
RM           5.74100
AGE         66.20000
DIS          7.22540
RAD          8.00000
TAX        284.00000
PTRATIO     19.70000
B          395.11000
LSTAT       13.15000
Name: 60, dtype: float64
CRIM         0.17171
ZN          25.00000
INDUS        5.13000
CHAS         0.00000
NOX          0.45300
RM           5.96600
AGE         93.40000
DIS          6.81850
RAD          8.00000
TAX        284.00000
PTRATIO     19.70000
B          378.08000
LSTAT       14.44000
Name: 61, dtype: float64
CRIM         0.11027
ZN          25.00000
INDUS        5.13000
CHAS         0.00000
NOX          0.45300
RM           6.45600
AGE         67.80000
DIS          7.22550
RAD          8.00000
TAX        284.00000
PTRATIO     19.70000
B          396.90000
LSTAT        6.73000
Name: 62, dtype: float64
CRIM         0.1265
ZN          25.0000
INDUS        5.1300
CHAS         0.0000
NOX          0.4530
RM           6.7620
AGE         43.4000
DIS          7.9809
RAD          8.0000
TAX        284.0000
PTRATIO     19.7000
B          395.5800
LSTAT        9.5000
Name: 63, dtype: float64
CRIM         0.08826
ZN           0.00000
INDUS       10.81000
CHAS         0.00000
NOX          0.41300
RM           6.41700
AGE          6.60000
DIS          5.28730
RAD          4.00000
TAX        305.00000
PTRATIO     19.20000
B          383.73000
LSTAT        6.72000
Name: 70, dtype: float64
CRIM         0.15876
ZN           0.00000
INDUS       10.81000
CHAS         0.00000
NOX          0.41300
RM           5.96100
AGE         17.50000
DIS          5.28730
RAD          4.00000
TAX        305.00000
PTRATIO     19.20000
B          376.94000
LSTAT        9.88000
Name: 71, dtype: float64
CRIM         0.09164
ZN           0.00000
INDUS       10.81000
CHAS         0.00000
NOX          0.41300
RM           6.06500
AGE          7.80000
DIS          5.28730
RAD          4.00000
TAX        305.00000
PTRATIO     19.20000
B          390.91000
LSTAT        5.52000
Name: 72, dtype: float64
CRIM         0.19539
ZN           0.00000
INDUS       10.81000
CHAS         0.00000
NOX          0.41300
RM           6.24500
AGE          6.20000
DIS          5.28730
RAD          4.00000
TAX        305.00000
PTRATIO     19.20000
B          377.17000
LSTAT        7.54000
Name: 73, dtype: float64
CRIM         0.04462
ZN          25.00000
INDUS        4.86000
CHAS         0.00000
NOX          0.42600
RM           6.61900
AGE         70.40000
DIS          5.40070
RAD          4.00000
TAX        281.00000
PTRATIO     19.00000
B          395.63000
LSTAT        7.22000
Name: 81, dtype: float64
CRIM         0.03551
ZN          25.00000
INDUS        4.86000
CHAS         0.00000
NOX          0.42600
RM           6.16700
AGE         46.70000
DIS          5.40070
RAD          4.00000
TAX        281.00000
PTRATIO     19.00000
B          390.64000
LSTAT        7.51000
Name: 83, dtype: float64
CRIM         0.0566
ZN           0.0000
INDUS        3.4100
CHAS         0.0000
NOX          0.4890
RM           7.0070
AGE         86.3000
DIS          3.4217
RAD          2.0000
TAX        270.0000
PTRATIO     17.8000
B          396.9000
LSTAT        5.5000
Name: 88, dtype: float64
CRIM         0.05302
ZN           0.00000
INDUS        3.41000
CHAS         0.00000
NOX          0.48900
RM           7.07900
AGE         63.10000
DIS          3.41450
RAD          2.00000
TAX        270.00000
PTRATIO     17.80000
B          396.06000
LSTAT        5.70000
Name: 89, dtype: float64
CRIM         0.04684
ZN           0.00000
INDUS        3.41000
CHAS         0.00000
NOX          0.48900
RM           6.41700
AGE         66.10000
DIS          3.09230
RAD          2.00000
TAX        270.00000
PTRATIO     17.80000
B          392.18000
LSTAT        8.81000
Name: 90, dtype: float64
CRIM         0.03932
ZN           0.00000
INDUS        3.41000
CHAS         0.00000
NOX          0.48900
RM           6.40500
AGE         73.90000
DIS          3.09210
RAD          2.00000
TAX        270.00000
PTRATIO     17.80000
B          393.55000
LSTAT        8.20000
Name: 91, dtype: float64
CRIM         0.04203
ZN          28.00000
INDUS       15.04000
CHAS         0.00000
NOX          0.46400
RM           6.44200
AGE         53.60000
DIS          3.66590
RAD          4.00000
TAX        270.00000
PTRATIO     18.20000
B          395.01000
LSTAT        8.16000
Name: 92, dtype: float64
CRIM         0.04294
ZN          28.00000
INDUS       15.04000
CHAS         0.00000
NOX          0.46400
RM           6.24900
AGE         77.30000
DIS          3.61500
RAD          4.00000
TAX        270.00000
PTRATIO     18.20000
B          396.90000
LSTAT       10.59000
Name: 94, dtype: float64
CRIM         0.12204
ZN           0.00000
INDUS        2.89000
CHAS         0.00000
NOX          0.44500
RM           6.62500
AGE         57.80000
DIS          3.49520
RAD          2.00000
TAX        276.00000
PTRATIO     18.00000
B          357.98000
LSTAT        6.65000
Name: 95, dtype: float64
CRIM         0.11504
ZN           0.00000
INDUS        2.89000
CHAS         0.00000
NOX          0.44500
RM           6.16300
AGE         69.60000
DIS          3.49520
RAD          2.00000
TAX        276.00000
PTRATIO     18.00000
B          391.83000
LSTAT       11.34000
Name: 96, dtype: float64
CRIM         0.12083
ZN           0.00000
INDUS        2.89000
CHAS         0.00000
NOX          0.44500
RM           8.06900
AGE         76.00000
DIS          3.49520
RAD          2.00000
TAX        276.00000
PTRATIO     18.00000
B          396.90000
LSTAT        4.21000
Name: 97, dtype: float64
CRIM         0.08187
ZN           0.00000
INDUS        2.89000
CHAS         0.00000
NOX          0.44500
RM           7.82000
AGE         36.90000
DIS          3.49520
RAD          2.00000
TAX        276.00000
PTRATIO     18.00000
B          393.53000
LSTAT        3.57000
Name: 98, dtype: float64
CRIM         0.0686
ZN           0.0000
INDUS        2.8900
CHAS         0.0000
NOX          0.4450
RM           7.4160
AGE         62.5000
DIS          3.4952
RAD          2.0000
TAX        276.0000
PTRATIO     18.0000
B          396.9000
LSTAT        6.1900
Name: 99, dtype: float64
CRIM         0.13914
ZN           0.00000
INDUS        4.05000
CHAS         0.00000
NOX          0.51000
RM           5.57200
AGE         88.50000
DIS          2.59610
RAD          5.00000
TAX        296.00000
PTRATIO     16.60000
B          396.90000
LSTAT       14.69000
Name: 172, dtype: float64
CRIM         0.09178
ZN           0.00000
INDUS        4.05000
CHAS         0.00000
NOX          0.51000
RM           6.41600
AGE         84.10000
DIS          2.64630
RAD          5.00000
TAX        296.00000
PTRATIO     16.60000
B          395.50000
LSTAT        9.04000
Name: 173, dtype: float64
CRIM         0.08447
ZN           0.00000
INDUS        4.05000
CHAS         0.00000
NOX          0.51000
RM           5.85900
AGE         68.70000
DIS          2.70190
RAD          5.00000
TAX        296.00000
PTRATIO     16.60000
B          393.23000
LSTAT        9.64000
Name: 174, dtype: float64
CRIM         0.06664
ZN           0.00000
INDUS        4.05000
CHAS         0.00000
NOX          0.51000
RM           6.54600
AGE         33.10000
DIS          3.13230
RAD          5.00000
TAX        296.00000
PTRATIO     16.60000
B          390.96000
LSTAT        5.33000
Name: 175, dtype: float64
CRIM         0.07022
ZN           0.00000
INDUS        4.05000
CHAS         0.00000
NOX          0.51000
RM           6.02000
AGE         47.20000
DIS          3.55490
RAD          5.00000
TAX        296.00000
PTRATIO     16.60000
B          393.23000
LSTAT       10.11000
Name: 176, dtype: float64
CRIM         0.05425
ZN           0.00000
INDUS        4.05000
CHAS         0.00000
NOX          0.51000
RM           6.31500
AGE         73.40000
DIS          3.31750
RAD          5.00000
TAX        296.00000
PTRATIO     16.60000
B          395.60000
LSTAT        6.29000
Name: 177, dtype: float64
CRIM         0.06642
ZN           0.00000
INDUS        4.05000
CHAS         0.00000
NOX          0.51000
RM           6.86000
AGE         74.40000
DIS          2.91530
RAD          5.00000
TAX        296.00000
PTRATIO     16.60000
B          391.27000
LSTAT        6.92000
Name: 178, dtype: float64
CRIM         0.13642
ZN           0.00000
INDUS       10.59000
CHAS         0.00000
NOX          0.48900
RM           5.89100
AGE         22.30000
DIS          3.94540
RAD          4.00000
TAX        277.00000
PTRATIO     18.60000
B          396.90000
LSTAT       10.87000
Name: 205, dtype: float64
CRIM         0.22969
ZN           0.00000
INDUS       10.59000
CHAS         0.00000
NOX          0.48900
RM           6.32600
AGE         52.50000
DIS          4.35490
RAD          4.00000
TAX        277.00000
PTRATIO     18.60000
B          394.87000
LSTAT       10.97000
Name: 206, dtype: float64
CRIM         0.25199
ZN           0.00000
INDUS       10.59000
CHAS         0.00000
NOX          0.48900
RM           5.78300
AGE         72.70000
DIS          4.35490
RAD          4.00000
TAX        277.00000
PTRATIO     18.60000
B          389.43000
LSTAT       18.06000
Name: 207, dtype: float64
CRIM         0.13587
ZN           0.00000
INDUS       10.59000
CHAS         1.00000
NOX          0.48900
RM           6.06400
AGE         59.10000
DIS          4.23920
RAD          4.00000
TAX        277.00000
PTRATIO     18.60000
B          381.32000
LSTAT       14.66000
Name: 208, dtype: float64
CRIM         0.43571
ZN           0.00000
INDUS       10.59000
CHAS         1.00000
NOX          0.48900
RM           5.34400
AGE        100.00000
DIS          3.87500
RAD          4.00000
TAX        277.00000
PTRATIO     18.60000
B          396.90000
LSTAT       23.09000
Name: 209, dtype: float64
CRIM         0.17446
ZN           0.00000
INDUS       10.59000
CHAS         1.00000
NOX          0.48900
RM           5.96000
AGE         92.10000
DIS          3.87710
RAD          4.00000
TAX        277.00000
PTRATIO     18.60000
B          393.25000
LSTAT       17.27000
Name: 210, dtype: float64
CRIM         0.37578
ZN           0.00000
INDUS       10.59000

Name: 230, dtype: float64
CRIM         0.46296
ZN           0.00000
INDUS        6.20000
CHAS         0.00000
NOX          0.50400
RM           7.41200
AGE         76.90000
DIS          3.67150
RAD          8.00000
TAX        307.00000
PTRATIO     17.40000
B          376.14000
LSTAT        5.25000
Name: 231, dtype: float64
CRIM         0.57529
ZN           0.00000
INDUS        6.20000
CHAS         0.00000
NOX          0.50700
RM           8.33700
AGE         73.30000
DIS          3.83840
RAD          8.00000
TAX        307.00000
PTRATIO     17.40000
B          385.91000
LSTAT        2.47000
Name: 232, dtype: float64
CRIM         0.33147
ZN           0.00000
INDUS        6.20000
CHAS         0.00000
NOX          0.50700
RM           8.24700
AGE         70.40000
DIS          3.65190
RAD          8.00000
TAX        307.00000
PTRATIO     17.40000
B          378.95000
LSTAT        3.95000
Name: 233, dtype: float64
CRIM         0.44791
ZN           0.00000
INDUS        6.20000
CHAS         1.00000
NOX          0.50700
RM           6.72600
AGE         66.50000
DIS          3.65190
RAD          8.00000
TAX        307.00000
PTRATIO     17.40000
B          360.20000
LSTAT        8.05000
Name: 234, dtype: float64
CRIM         0.33045
ZN           0.00000
INDUS        6.20000
CHAS         0.00000
NOX          0.50700
RM           6.08600
AGE         61.50000
DIS          3.65190
RAD          8.00000
TAX        307.00000
PTRATIO     17.40000
B          376.75000
LSTAT       10.88000
Name: 235, dtype: float64
CRIM         0.52058
ZN           0.00000
INDUS        6.20000
CHAS         1.00000
NOX          0.50700
RM           6.63100
AGE         76.50000
DIS          4.14800
RAD          8.00000
TAX        307.00000
PTRATIO     17.40000
B          388.45000
LSTAT        9.54000
Name: 236, dtype: float64
CRIM         0.51183
ZN           0.00000
INDUS        6.20000
CHAS         0.00000
NOX          0.50700
RM           7.35800
AGE         71.60000
DIS          4.14800
RAD          8.00000
TAX        307.00000
PTRATIO     17.40000
B          390.07000
LSTAT        4.73000
Name: 237, dtype: float64
CRIM         0.09252
ZN          30.00000
INDUS        4.93000
CHAS         0.00000
NOX          0.42800
RM           6.60600
AGE         42.20000
DIS          6.18990
RAD          6.00000
TAX        300.00000
PTRATIO     16.60000
B          383.78000
LSTAT        7.37000
Name: 239, dtype: float64
CRIM         0.11329
ZN          30.00000
INDUS        4.93000
CHAS         0.00000
NOX          0.42800
RM           6.89700
AGE         54.30000
DIS          6.33610
RAD          6.00000
TAX        300.00000
PTRATIO     16.60000
B          391.25000
LSTAT       11.38000
Name: 240, dtype: float64
CRIM         0.10612
ZN          30.00000
INDUS        4.93000
CHAS         0.00000
NOX          0.42800
RM           6.09500
AGE         65.10000
DIS          6.33610
RAD          6.00000
TAX        300.00000
PTRATIO     16.60000
B          394.62000
LSTAT       12.40000
Name: 241, dtype: float64
CRIM         0.1029
ZN          30.0000
INDUS        4.9300
CHAS         0.0000
NOX          0.4280
RM           6.3580
AGE         52.9000
DIS          7.0355
RAD          6.0000
TAX        300.0000
PTRATIO     16.6000
B          372.7500
LSTAT       11.2200
Name: 242, dtype: float64
CRIM         0.20608
ZN          22.00000
INDUS        5.86000
CHAS         0.00000
NOX          0.43100
RM           5.59300
AGE         76.50000
DIS          7.95490
RAD          7.00000
TAX        330.00000
PTRATIO     19.10000
B          372.49000
LSTAT       12.50000
Name: 244, dtype: float64
CRIM         0.19133
ZN          22.00000
INDUS        5.86000
CHAS         0.00000
NOX          0.43100
RM           5.60500
AGE         70.20000
DIS          7.95490
RAD          7.00000
TAX        330.00000
PTRATIO     19.10000
B          389.13000
LSTAT       18.46000
Name: 245, dtype: float64
CRIM         0.19657
ZN          22.00000
INDUS        5.86000
CHAS         0.00000
NOX          0.43100
RM           6.22600
AGE         79.20000
DIS          8.05550
RAD          7.00000
TAX        330.00000
PTRATIO     19.10000
B          376.14000
LSTAT       10.15000
Name: 247, dtype: float64
CRIM         0.61154
ZN          20.00000
INDUS        3.97000
CHAS         0.00000
NOX          0.64700
RM           8.70400
AGE         86.90000
DIS          1.80100
RAD          5.00000
TAX        264.00000
PTRATIO     13.00000
B          389.70000
LSTAT        5.12000
Name: 257, dtype: float64
CRIM         0.66351
ZN          20.00000
INDUS        3.97000
CHAS         0.00000
NOX          0.64700
RM           7.33300
AGE        100.00000
DIS          1.89460
RAD          5.00000
TAX        264.00000
PTRATIO     13.00000
B          383.29000
LSTAT        7.79000
Name: 258, dtype: float64
CRIM         0.65665
ZN          20.00000
INDUS        3.97000
CHAS         0.00000
NOX          0.64700
RM           6.84200
AGE        100.00000
DIS          2.01070
RAD          5.00000
TAX        264.00000
PTRATIO     13.00000
B          391.93000
LSTAT        6.90000
Name: 259, dtype: float64
CRIM         0.54011
ZN          20.00000
INDUS        3.97000
CHAS         0.00000
NOX          0.64700
RM           7.20300
AGE         81.80000
DIS          2.11210
RAD          5.00000
TAX        264.00000
PTRATIO     13.00000
B          392.80000
LSTAT        9.59000
Name: 260, dtype: float64
CRIM         0.53412
ZN          20.00000
INDUS        3.97000
CHAS         0.00000
NOX          0.64700
RM           7.52000
AGE         89.40000
DIS          2.13980
RAD          5.00000
TAX        264.00000
PTRATIO     13.00000
B          388.37000
LSTAT        7.26000
Name: 261, dtype: float64
CRIM         0.52014
ZN          20.00000
INDUS        3.97000
CHAS         0.00000
NOX          0.64700
RM           8.39800
AGE         91.50000
DIS          2.28850
RAD          5.00000
TAX        264.00000
PTRATIO     13.00000
B          386.86000
LSTAT        5.91000
Name: 262, dtype: float64
CRIM         0.82526
ZN          20.00000
INDUS        3.97000
CHAS         0.00000
NOX          0.64700
RM           7.32700
AGE         94.50000
DIS          2.07880
RAD          5.00000
TAX        264.00000
PTRATIO     13.00000
B          393.42000
LSTAT       11.25000
Name: 263, dtype: float64
CRIM         0.55007
ZN          20.00000
INDUS        3.97000
CHAS         0.00000
NOX          0.64700
RM           7.20600
AGE         91.60000
DIS          1.93010
RAD          5.00000
TAX        264.00000
PTRATIO     13.00000
B          387.89000
LSTAT        8.10000
Name: 264, dtype: float64
CRIM         0.76162
ZN          20.00000
INDUS        3.97000
CHAS         0.00000
NOX          0.64700
RM           5.56000
AGE         62.80000
DIS          1.98650
RAD          5.00000
TAX        264.00000
PTRATIO     13.00000
B          392.40000
LSTAT       10.45000
Name: 265, dtype: float64
CRIM         0.7857
ZN          20.0000
INDUS        3.9700
CHAS         0.0000
NOX          0.6470
RM           7.0140
AGE         84.6000
DIS          2.1329
RAD          5.0000
TAX        264.0000
PTRATIO     13.0000
B          384.0700
LSTAT       14.7900
Name: 266, dtype: float64
CRIM         0.57834
ZN          20.00000
INDUS        3.97000
CHAS         0.00000
NOX          0.57500
RM           8.29700
AGE         67.00000
DIS          2.42160
RAD          5.00000
TAX        264.00000
PTRATIO     13.00000
B          384.54000
LSTAT        7.44000
Name: 267, dtype: float64
CRIM         0.5405
ZN          20.0000
INDUS        3.9700
CHAS         0.0000
NOX          0.5750
RM           7.4700
AGE         52.6000
DIS          2.8720
RAD          5.0000
TAX        264.0000
PTRATIO     13.0000
B          390.3000
LSTAT        3.1600
Name: 268, dtype: float64
CRIM         0.08265
ZN           0.00000
INDUS       13.92000
CHAS         0.00000
NOX          0.43700
RM           6.12700
AGE         18.40000
DIS          5.50270
RAD          4.00000
TAX        289.00000
PTRATIO     16.00000
B          396.90000
LSTAT        8.58000
Name: 293, dtype: float64
CRIM         0.08199
ZN           0.00000
INDUS       13.92000
CHAS         0.00000
NOX          0.43700
RM           6.00900
AGE         42.30000
DIS          5.50270
RAD          4.00000
TAX        289.00000
PTRATIO     16.00000
B          396.90000
LSTAT       10.40000
Name: 294, dtype: float64
CRIM         0.12932
ZN           0.00000
INDUS       13.92000
CHAS         0.00000
NOX          0.43700
RM           6.67800
AGE         31.10000
DIS          5.96040
RAD          4.00000
TAX        289.00000
PTRATIO     16.00000
B          396.90000
LSTAT        6.27000
Name: 295, dtype: float64
CRIM         0.05372
ZN           0.00000
INDUS       13.92000
CHAS         0.00000
NOX          0.43700
RM           6.54900
AGE         51.00000
DIS          5.96040
RAD          4.00000
TAX        289.00000
PTRATIO     16.00000
B          392.85000
LSTAT        7.39000
Name: 296, dtype: float64
CRIM         0.14103
ZN           0.00000
INDUS       13.92000
CHAS         0.00000
NOX          0.43700
RM           5.79000
AGE         58.00000
DIS          6.32000
RAD          4.00000
TAX        289.00000
PTRATIO     16.00000
B          396.90000
LSTAT       15.84000
Name: 297, dtype: float64
CRIM         0.49298
ZN           0.00000
INDUS        9.90000
CHAS         0.00000
NOX          0.54400
RM           6.63500
AGE         82.50000
DIS          3.31750
RAD          4.00000
TAX        304.00000
PTRATIO     18.40000
B          396.90000
LSTAT        4.54000
Name: 308, dtype: float64
CRIM         0.3494
ZN           0.0000
INDUS        9.9000
CHAS         0.0000
NOX          0.5440
RM           5.9720
AGE         76.7000
DIS          3.1025
RAD          4.0000
TAX        304.0000
PTRATIO     18.4000
B          396.2400
LSTAT        9.9700
Name: 309, dtype: float64
CRIM         2.63548
ZN           0.00000
INDUS        9.90000
CHAS         0.00000
NOX          0.54400
RM           4.97300
AGE         37.80000
DIS          2.51940
RAD          4.00000
TAX        304.00000
PTRATIO     18.40000
B          350.45000
LSTAT       12.64000
Name: 310, dtype: float64
CRIM         0.79041
ZN           0.00000
INDUS        9.90000
CHAS         0.00000
NOX          0.54400
RM           6.12200
AGE         52.80000
DIS          2.64030
RAD          4.00000
TAX        304.00000
PTRATIO     18.40000
B          396.90000
LSTAT        5.98000
Name: 311, dtype: float64
CRIM         0.26169
ZN           0.00000
INDUS        9.90000
CHAS         0.00000
NOX          0.54400
RM           6.02300
AGE         90.40000
DIS          2.83400
RAD          4.00000
TAX        304.00000
PTRATIO     18.40000
B          396.30000
LSTAT       11.72000
Name: 312, dtype: float64
CRIM         0.26938
ZN           0.00000
INDUS        9.90000
CHAS         0.00000
NOX          0.54400
RM           6.26600
AGE         82.80000
DIS          3.26280
RAD          4.00000
TAX        304.00000
PTRATIO     18.40000
B          393.39000
LSTAT        7.90000

Name: 313, dtype: float64
CRIM         0.3692
ZN           0.0000
INDUS        9.9000
CHAS         0.0000
NOX          0.5440
RM           6.5670
AGE         87.3000
DIS          3.6023
RAD          4.0000
TAX        304.0000
PTRATIO     18.4000
B          395.6900
LSTAT        9.2800
Name: 314, dtype: float64
CRIM         0.25356
ZN           0.00000
INDUS        9.90000
CHAS         0.00000
NOX          0.54400
RM           5.70500
AGE         77.70000
DIS          3.94500
RAD          4.00000
TAX        304.00000
PTRATIO     18.40000
B          396.42000
LSTAT       11.50000
Name: 315, dtype: float64
CRIM         0.31827
ZN           0.00000
INDUS        9.90000
CHAS         0.00000
NOX          0.54400
RM           5.91400
AGE         83.20000
DIS          3.99860
RAD          4.00000
TAX        304.00000
PTRATIO     18.40000
B          390.70000
LSTAT       18.33000
Name: 316, dtype: float64
CRIM         0.24522
ZN           0.00000
INDUS        9.90000
CHAS         0.00000
NOX          0.54400
RM           5.78200
AGE         71.70000
DIS          4.03170
RAD          4.00000
TAX        304.00000
PTRATIO     18.40000
B          396.90000
LSTAT       15.94000
Name: 317, dtype: float64
CRIM         0.40202
ZN           0.00000
INDUS        9.90000
CHAS         0.00000
NOX          0.54400
RM           6.38200
AGE         67.20000
DIS          3.53250
RAD          4.00000
TAX        304.00000
PTRATIO     18.40000
B          395.21000
LSTAT       10.36000
Name: 318, dtype: float64
CRIM         0.47547
ZN           0.00000
INDUS        9.90000
CHAS         0.00000
NOX          0.54400
RM           6.11300
AGE         58.80000
DIS          4.00190
RAD          4.00000
TAX        304.00000
PTRATIO     18.40000
B          396.23000
LSTAT       12.73000
Name: 319, dtype: float64
CRIM         0.1676
ZN           0.0000
INDUS        7.3800
CHAS         0.0000
NOX          0.4930
RM           6.4260
AGE         52.3000
DIS          4.5404
RAD          5.0000
TAX        287.0000
PTRATIO     19.6000
B          396.9000
LSTAT        7.2000
Name: 320, dtype: float64
CRIM         0.18159
ZN           0.00000
INDUS        7.38000
CHAS         0.00000
NOX          0.49300
RM           6.37600
AGE         54.30000
DIS          4.54040
RAD          5.00000
TAX        287.00000
PTRATIO     19.60000
B          396.90000
LSTAT        6.87000
Name: 321, dtype: float64
CRIM         0.35114
ZN           0.00000
INDUS        7.38000
CHAS         0.00000
NOX          0.49300
RM           6.04100
AGE         49.90000
DIS          4.72110
RAD          5.00000
TAX        287.00000
PTRATIO     19.60000
B          396.90000
LSTAT        7.70000
Name: 322, dtype: float64
CRIM         0.28392
ZN           0.00000
INDUS        7.38000
CHAS         0.00000
NOX          0.49300
RM           5.70800
AGE         74.30000
DIS          4.72110
RAD          5.00000
TAX        287.00000
PTRATIO     19.60000
B          391.13000
LSTAT       11.74000
Name: 323, dtype: float64
CRIM         0.34109
ZN           0.00000
INDUS        7.38000
CHAS         0.00000
NOX          0.49300
RM           6.41500
AGE         40.10000
DIS          4.72110
RAD          5.00000
TAX        287.00000
PTRATIO     19.60000
B          396.90000
LSTAT        6.12000
Name: 324, dtype: float64
CRIM         0.19186
ZN           0.00000
INDUS        7.38000
CHAS         0.00000
NOX          0.49300
RM           6.43100
AGE         14.70000
DIS          5.41590
RAD          5.00000
TAX        287.00000
PTRATIO     19.60000
B          393.68000
LSTAT        5.08000
Name: 325, dtype: float64
CRIM         0.30347
ZN           0.00000
INDUS        7.38000
CHAS         0.00000
NOX          0.49300
RM           6.31200
AGE         28.90000
DIS          5.41590
RAD          5.00000
TAX        287.00000
PTRATIO     19.60000
B          396.90000
LSTAT        6.15000
Name: 326, dtype: float64
CRIM         0.24103
ZN           0.00000
INDUS        7.38000
CHAS         0.00000
NOX          0.49300
RM           6.08300
AGE         43.70000
DIS          5.41590
RAD          5.00000
TAX        287.00000
PTRATIO     19.60000
B          396.90000
LSTAT       12.79000
Name: 327, dtype: float64
CRIM         0.01301
ZN          35.00000
INDUS        1.52000
CHAS         0.00000
NOX          0.44200
RM           7.24100
AGE         49.30000
DIS          7.03790
RAD          1.00000
TAX        284.00000
PTRATIO     15.50000
B          394.74000
LSTAT        5.49000
Name: 341, dtype: float64
CRIM         0.06263
ZN           0.00000
INDUS       11.93000
CHAS         0.00000
NOX          0.57300
RM           6.59300
AGE         69.10000
DIS          2.47860
RAD          1.00000
TAX        273.00000
PTRATIO     21.00000
B          391.99000
LSTAT        9.67000
Name: 501, dtype: float64
CRIM         0.04527
ZN           0.00000
INDUS       11.93000
CHAS         0.00000
NOX          0.57300
RM           6.12000
AGE         76.70000
DIS          2.28750
RAD          1.00000
TAX        273.00000
PTRATIO     21.00000
B          396.90000
LSTAT        9.08000
Name: 502, dtype: float64
CRIM         0.06076
ZN           0.00000
INDUS       11.93000
CHAS         0.00000
NOX          0.57300
RM           6.97600
AGE         91.00000
DIS          2.16750
RAD          1.00000
TAX        273.00000
PTRATIO     21.00000
B          396.90000
LSTAT        5.64000
Name: 503, dtype: float64
CRIM         0.10959
ZN           0.00000
INDUS       11.93000
CHAS         0.00000
NOX          0.57300
RM           6.79400
AGE         89.30000
DIS          2.38890
RAD          1.00000
TAX        273.00000
PTRATIO     21.00000
B          393.45000
LSTAT        6.48000
Name: 504, dtype: float64
CRIM         0.04741
ZN           0.00000
INDUS       11.93000
CHAS         0.00000
NOX          0.57300
RM           6.03000
AGE         80.80000
DIS          2.50500
RAD          1.00000
TAX        273.00000
PTRATIO     21.00000
B          396.90000
LSTAT        7.88000
Name: 505, dtype: float64
Cluster  5
CRIM         0.02731
ZN           0.00000
INDUS        7.07000
CHAS         0.00000
NOX          0.46900
RM           6.42100
AGE         78.90000
DIS          4.96710
RAD          2.00000
TAX        242.00000
PTRATIO     17.80000
B          396.90000
LSTAT        9.14000
Name: 1, dtype: float64
CRIM         0.02729
ZN           0.00000
INDUS        7.07000
CHAS         0.00000
NOX          0.46900
RM           7.18500
AGE         61.10000
DIS          4.96710
RAD          2.00000
TAX        242.00000
PTRATIO     17.80000
B          392.83000
LSTAT        4.03000
Name: 2, dtype: float64
CRIM         0.03237
ZN           0.00000
INDUS        2.18000
CHAS         0.00000
NOX          0.45800
RM           6.99800
AGE         45.80000
DIS          6.06220
RAD          3.00000
TAX        222.00000
PTRATIO     18.70000
B          394.63000
LSTAT        2.94000
Name: 3, dtype: float64
CRIM         0.06905
ZN           0.00000
INDUS        2.18000
CHAS         0.00000
NOX          0.45800
RM           7.14700
AGE         54.20000
DIS          6.06220
RAD          3.00000
TAX        222.00000
PTRATIO     18.70000
B          396.90000
LSTAT        5.33000
Name: 4, dtype: float64
CRIM         0.02985
ZN           0.00000
INDUS        2.18000
CHAS         0.00000
NOX          0.45800
RM           6.43000
AGE         58.70000
DIS          6.06220
RAD          3.00000
TAX        222.00000
PTRATIO     18.70000
B          394.12000
LSTAT        5.21000
Name: 5, dtype: float64
CRIM         0.12744
ZN           0.00000
INDUS        6.91000
CHAS         0.00000
NOX          0.44800
RM           6.77000
AGE          2.90000
DIS          5.72090
RAD          3.00000
TAX        233.00000
PTRATIO     17.90000
B          385.41000
LSTAT        4.84000
Name: 41, dtype: float64
CRIM         0.1415
ZN           0.0000
INDUS        6.9100
CHAS         0.0000
NOX          0.4480
RM           6.1690
AGE          6.6000
DIS          5.7209
RAD          3.0000
TAX        233.0000
PTRATIO     17.9000
B          383.3700
LSTAT        5.8100
Name: 42, dtype: float64
CRIM         0.15936
ZN           0.00000
INDUS        6.91000
CHAS         0.00000
NOX          0.44800
RM           6.21100
AGE          6.50000
DIS          5.72090
RAD          3.00000
TAX        233.00000
PTRATIO     17.90000
B          394.46000
LSTAT        7.44000
Name: 43, dtype: float64
CRIM         0.12269
ZN           0.00000
INDUS        6.91000
CHAS         0.00000
NOX          0.44800
RM           6.06900
AGE         40.00000
DIS          5.72090
RAD          3.00000
TAX        233.00000
PTRATIO     17.90000
B          389.39000
LSTAT        9.55000
Name: 44, dtype: float64
CRIM         0.17142
ZN           0.00000
INDUS        6.91000
CHAS         0.00000
NOX          0.44800
RM           5.68200
AGE         33.80000
DIS          5.10040
RAD          3.00000
TAX        233.00000
PTRATIO     17.90000
B          396.90000
LSTAT       10.21000
Name: 45, dtype: float64
CRIM         0.18836
ZN           0.00000
INDUS        6.91000
CHAS         0.00000
NOX          0.44800
RM           5.78600
AGE         33.30000
DIS          5.10040
RAD          3.00000
TAX        233.00000
PTRATIO     17.90000
B          396.90000
LSTAT       14.15000
Name: 46, dtype: float64
CRIM         0.22927
ZN           0.00000
INDUS        6.91000
CHAS         0.00000
NOX          0.44800
RM           6.03000
AGE         85.50000
DIS          5.68940
RAD          3.00000
TAX        233.00000
PTRATIO     17.90000
B          392.74000
LSTAT       18.80000
Name: 47, dtype: float64
CRIM         0.25387
ZN           0.00000
INDUS        6.91000
CHAS         0.00000
NOX          0.44800
RM           5.39900
AGE         95.30000
DIS          5.87000
RAD          3.00000
TAX        233.00000
PTRATIO     17.90000
B          396.90000
LSTAT       30.81000
Name: 48, dtype: float64
CRIM         0.21977
ZN           0.00000
INDUS        6.91000
CHAS         0.00000
NOX          0.44800
RM           5.60200
AGE         62.00000
DIS          6.08770
RAD          3.00000
TAX        233.00000
PTRATIO     17.90000
B          396.90000
LSTAT       16.20000
Name: 49, dtype: float64
CRIM         0.08873
ZN          21.00000
INDUS        5.64000
CHAS         0.00000
NOX          0.43900
RM           5.96300
AGE         45.70000
DIS          6.81470
RAD          4.00000
TAX        243.00000
PTRATIO     16.80000
B          395.56000
LSTAT       13.45000
Name: 50, dtype: float64
CRIM         0.04337
ZN          21.00000
INDUS        5.64000
CHAS         0.00000
NOX          0.43900
RM           6.11500
AGE         63.00000
DIS          6.81470
RAD          4.00000
TAX        243.00000
PTRATIO     16.80000
B          393.97000
LSTAT        9.43000
Name: 51, dtype: float64
CRIM         0.01951
ZN          17.50000
INDUS        1.38000
CHAS         0.00000
NOX          0.41610
RM           7.10400
AGE         59.50000
DIS          9.22290
RAD          3.00000
TAX        216.00000
PTRATIO     18.60000
B          393.24000
LSTAT        8.05000
Name: 64, dtype: float64
CRIM         0.05059
ZN           0.00000
INDUS        4.49000
CHAS         0.00000
NOX          0.44900
RM           6.38900
AGE         48.00000
DIS          4.77940
RAD          3.00000
TAX        247.00000
PTRATIO     18.50000
B          396.90000
LSTAT        9.62000
Name: 84, dtype: float64
CRIM         0.05735
ZN           0.00000
INDUS        4.49000
CHAS         0.00000
NOX          0.44900
RM           6.63000
AGE         56.10000
DIS          4.43770
RAD          3.00000
TAX        247.00000
PTRATIO     18.50000
B          392.30000
LSTAT        6.53000
Name: 85, dtype: float64
CRIM         0.05188
ZN           0.00000
INDUS        4.49000
CHAS         0.00000
NOX          0.44900
RM           6.01500
AGE         45.10000
DIS          4.42720
RAD          3.00000
TAX        247.00000
PTRATIO     18.50000
B          395.99000
LSTAT       12.86000
Name: 86, dtype: float64
CRIM         0.07151
ZN           0.00000
INDUS        4.49000
CHAS         0.00000
NOX          0.44900
RM           6.12100
AGE         56.80000
DIS          3.74760
RAD          3.00000
TAX        247.00000
PTRATIO     18.50000
B          395.15000
LSTAT        8.44000
Name: 87, dtype: float64
CRIM         0.06899
ZN           0.00000
INDUS       25.65000
CHAS         0.00000
NOX          0.58100
RM           5.87000
AGE         69.70000
DIS          2.25770
RAD          2.00000
TAX        188.00000
PTRATIO     19.10000
B          389.15000
LSTAT       14.37000
Name: 120, dtype: float64
CRIM         0.07165
ZN           0.00000
INDUS       25.65000
CHAS         0.00000
NOX          0.58100
RM           6.00400
AGE         84.10000
DIS          2.19740
RAD          2.00000
TAX        188.00000
PTRATIO     19.10000
B          377.67000
LSTAT       14.27000
Name: 121, dtype: float64
CRIM         0.09299
ZN           0.00000
INDUS       25.65000
CHAS         0.00000
NOX          0.58100
RM           5.96100
AGE         92.90000
DIS          2.08690
RAD          2.00000
TAX        188.00000
PTRATIO     19.10000
B          378.09000
LSTAT       17.93000
Name: 122, dtype: float64
CRIM         0.15038
ZN           0.00000
INDUS       25.65000
CHAS         0.00000
NOX          0.58100
RM           5.85600
AGE         97.00000
DIS          1.94440
RAD          2.00000
TAX        188.00000
PTRATIO     19.10000
B          370.31000
LSTAT       25.41000
Name: 123, dtype: float64
CRIM         0.09849
ZN           0.00000
INDUS       25.65000
CHAS         0.00000
NOX          0.58100
RM           5.87900
AGE         95.80000
DIS          2.00630
RAD          2.00000
TAX        188.00000
PTRATIO     19.10000
B          379.38000
LSTAT       17.58000
Name: 124, dtype: float64
CRIM         0.16902
ZN           0.00000
INDUS       25.65000
CHAS         0.00000
NOX          0.58100
RM           5.98600
AGE         88.40000
DIS          1.99290
RAD          2.00000
TAX        188.00000
PTRATIO     19.10000
B          385.02000
LSTAT       14.81000
Name: 125, dtype: float64
CRIM         0.38735
ZN           0.00000
INDUS       25.65000
CHAS         0.00000
NOX          0.58100
RM           5.61300
AGE         95.60000
DIS          1.75720
RAD          2.00000
TAX        188.00000
PTRATIO     19.10000
B          359.29000
LSTAT       27.26000
Name: 126, dtype: float64
CRIM         0.0578
ZN           0.0000
INDUS        2.4600
CHAS         0.0000
NOX          0.4880
RM           6.9800
AGE         58.4000
DIS          2.8290
RAD          3.0000
TAX        193.0000
PTRATIO     17.8000
B          396.9000
LSTAT        5.0400
Name: 179, dtype: float64
CRIM         0.06588
ZN           0.00000
INDUS        2.46000
CHAS         0.00000
NOX          0.48800
RM           7.76500
AGE         83.30000
DIS          2.74100
RAD          3.00000
TAX        193.00000
PTRATIO     17.80000
B          395.56000
LSTAT        7.56000
Name: 180, dtype: float64
CRIM         0.06888
ZN           0.00000
INDUS        2.46000
CHAS         0.00000
NOX          0.48800
RM           6.14400
AGE         62.20000
DIS          2.59790
RAD          3.00000
TAX        193.00000
PTRATIO     17.80000
B          396.90000
LSTAT        9.45000
Name: 181, dtype: float64
CRIM         0.09103
ZN           0.00000
INDUS        2.46000
CHAS         0.00000
NOX          0.48800
RM           7.15500
AGE         92.20000
DIS          2.70060
RAD          3.00000
TAX        193.00000
PTRATIO     17.80000
B          394.12000
LSTAT        4.82000
Name: 182, dtype: float64
CRIM         0.10008
ZN           0.00000
INDUS        2.46000
CHAS         0.00000
NOX          0.48800
RM           6.56300
AGE         95.60000
DIS          2.84700
RAD          3.00000
TAX        193.00000
PTRATIO     17.80000
B          396.90000
LSTAT        5.68000
Name: 183, dtype: float64
CRIM         0.08308
ZN           0.00000
INDUS        2.46000
CHAS         0.00000
NOX          0.48800
RM           5.60400
AGE         89.80000
DIS          2.98790
RAD          3.00000
TAX        193.00000
PTRATIO     17.80000
B          391.00000
LSTAT       13.98000
Name: 184, dtype: float64
CRIM         0.06047
ZN           0.00000
INDUS        2.46000
CHAS         0.00000
NOX          0.48800
RM           6.15300
AGE         68.80000
DIS          3.27970
RAD          3.00000
TAX        193.00000
PTRATIO     17.80000
B          387.11000
LSTAT       13.15000
Name: 185, dtype: float64
CRIM         0.05602
ZN           0.00000
INDUS        2.46000
CHAS         0.00000
NOX          0.48800
RM           7.83100
AGE         53.60000
DIS          3.19920
RAD          3.00000
TAX        193.00000
PTRATIO     17.80000
B          392.63000
LSTAT        4.45000
Name: 186, dtype: float64
CRIM         0.09065
ZN          20.00000
INDUS        6.96000
CHAS         1.00000
NOX          0.46400
RM           5.92000
AGE         61.50000
DIS          3.91750
RAD          3.00000
TAX        223.00000
PTRATIO     18.60000
B          391.34000
LSTAT       13.65000
Name: 269, dtype: float64
CRIM         0.29916
ZN          20.00000
INDUS        6.96000
CHAS         0.00000
NOX          0.46400
RM           5.85600
AGE         42.10000
DIS          4.42900
RAD          3.00000
TAX        223.00000
PTRATIO     18.60000
B          388.65000
LSTAT       13.00000
Name: 270, dtype: float64
CRIM         0.16211
ZN          20.00000
INDUS        6.96000
CHAS         0.00000
NOX          0.46400
RM           6.24000
AGE         16.30000
DIS          4.42900
RAD          3.00000
TAX        223.00000
PTRATIO     18.60000
B          396.90000
LSTAT        6.59000

Name: 271, dtype: float64
CRIM         0.1146
ZN          20.0000
INDUS        6.9600
CHAS         0.0000
NOX          0.4640
RM           6.5380
AGE         58.7000
DIS          3.9175
RAD          3.0000
TAX        223.0000
PTRATIO     18.6000
B          394.9600
LSTAT        7.7300
Name: 272, dtype: float64
CRIM         0.22188
ZN          20.00000
INDUS        6.96000
CHAS         1.00000
NOX          0.46400
RM           7.69100
AGE         51.80000
DIS          4.36650
RAD          3.00000
TAX        223.00000
PTRATIO     18.60000
B          390.77000
LSTAT        6.58000
Name: 273, dtype: float64
CRIM         0.21038
ZN          20.00000
INDUS        3.33000
CHAS         0.00000
NOX          0.44290
RM           6.81200
AGE         32.20000
DIS          4.10070
RAD          5.00000
TAX        216.00000
PTRATIO     14.90000
B          396.90000
LSTAT        4.85000
Name: 279, dtype: float64
CRIM         0.03578
ZN          20.00000
INDUS        3.33000
CHAS         0.00000
NOX          0.44290
RM           7.82000
AGE         64.50000
DIS          4.69470
RAD          5.00000
TAX        216.00000
PTRATIO     14.90000
B          387.31000
LSTAT        3.76000
Name: 280, dtype: float64
CRIM         0.03705
ZN          20.00000
INDUS        3.33000
CHAS         0.00000
NOX          0.44290
RM           6.96800
AGE         37.20000
DIS          5.24470
RAD          5.00000
TAX        216.00000
PTRATIO     14.90000
B          392.23000
LSTAT        4.59000
Name: 281, dtype: float64
CRIM         0.06129
ZN          20.00000
INDUS        3.33000
CHAS         1.00000
NOX          0.44290
RM           7.64500
AGE         49.70000
DIS          5.21190
RAD          5.00000
TAX        216.00000
PTRATIO     14.90000
B          377.07000
LSTAT        3.01000
Name: 282, dtype: float64
CRIM         0.05515
ZN          33.00000
INDUS        2.18000
CHAS         0.00000
NOX          0.47200
RM           7.23600
AGE         41.10000
DIS          4.02200
RAD          7.00000
TAX        222.00000
PTRATIO     18.40000
B          393.68000
LSTAT        6.93000
Name: 304, dtype: float64
CRIM         0.05479
ZN          33.00000
INDUS        2.18000
CHAS         0.00000
NOX          0.47200
RM           6.61600
AGE         58.10000
DIS          3.37000
RAD          7.00000
TAX        222.00000
PTRATIO     18.40000
B          393.36000
LSTAT        8.93000
Name: 305, dtype: float64
CRIM         0.07503
ZN          33.00000
INDUS        2.18000
CHAS         0.00000
NOX          0.47200
RM           7.42000
AGE         71.90000
DIS          3.09920
RAD          7.00000
TAX        222.00000
PTRATIO     18.40000
B          396.90000
LSTAT        6.47000
Name: 306, dtype: float64
CRIM         0.04932
ZN          33.00000
INDUS        2.18000
CHAS         0.00000
NOX          0.47200
RM           6.84900
AGE         70.30000
DIS          3.18270
RAD          7.00000
TAX        222.00000
PTRATIO     18.40000
B          396.90000
LSTAT        7.53000
Name: 307, dtype: float64
CRIM         0.05083
ZN           0.00000
INDUS        5.19000
CHAS         0.00000
NOX          0.51500
RM           6.31600
AGE         38.10000
DIS          6.45840
RAD          5.00000
TAX        224.00000
PTRATIO     20.20000
B          389.71000
LSTAT        5.68000
Name: 333, dtype: float64
CRIM         0.03738
ZN           0.00000
INDUS        5.19000
CHAS         0.00000
NOX          0.51500
RM           6.31000
AGE         38.50000
DIS          6.45840
RAD          5.00000
TAX        224.00000
PTRATIO     20.20000
B          389.40000
LSTAT        6.75000
Name: 334, dtype: float64
CRIM         0.03961
ZN           0.00000
INDUS        5.19000
CHAS         0.00000
NOX          0.51500
RM           6.03700
AGE         34.50000
DIS          5.98530
RAD          5.00000
TAX        224.00000
PTRATIO     20.20000
B          396.90000
LSTAT        8.01000
Name: 335, dtype: float64
CRIM         0.03427
ZN           0.00000
INDUS        5.19000
CHAS         0.00000
NOX          0.51500
RM           5.86900
AGE         46.30000
DIS          5.23110
RAD          5.00000
TAX        224.00000
PTRATIO     20.20000
B          396.90000
LSTAT        9.80000
Name: 336, dtype: float64
CRIM         0.03041
ZN           0.00000
INDUS        5.19000
CHAS         0.00000
NOX          0.51500
RM           5.89500
AGE         59.60000
DIS          5.61500
RAD          5.00000
TAX        224.00000
PTRATIO     20.20000
B          394.81000
LSTAT       10.56000
Name: 337, dtype: float64
CRIM         0.03306
ZN           0.00000
INDUS        5.19000
CHAS         0.00000
NOX          0.51500
RM           6.05900
AGE         37.30000
DIS          4.81220
RAD          5.00000
TAX        224.00000
PTRATIO     20.20000
B          396.14000
LSTAT        8.51000
Name: 338, dtype: float64
CRIM         0.05497
ZN           0.00000
INDUS        5.19000
CHAS         0.00000
NOX          0.51500
RM           5.98500
AGE         45.40000
DIS          4.81220
RAD          5.00000
TAX        224.00000
PTRATIO     20.20000
B          396.90000
LSTAT        9.74000
Name: 339, dtype: float64
CRIM         0.06151
ZN           0.00000
INDUS        5.19000
CHAS         0.00000
NOX          0.51500
RM           5.96800
AGE         58.50000
DIS          4.81220
RAD          5.00000
TAX        224.00000
PTRATIO     20.20000
B          396.90000
LSTAT        9.29000
Name: 340, dtype: float64
Cluster  6
CRIM         1.38799
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           5.95000
AGE         82.00000
DIS          3.99000
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          232.60000
LSTAT       27.71000
Name: 32, dtype: float64
CRIM         1.61282
ZN           0.00000
INDUS        8.14000
CHAS         0.00000
NOX          0.53800
RM           6.09600
AGE         96.90000
DIS          3.75980
RAD          4.00000
TAX        307.00000
PTRATIO     21.00000
B          248.31000
LSTAT       20.34000
Name: 34, dtype: float64
CRIM         0.22876
ZN           0.00000
INDUS        8.56000
CHAS         0.00000
NOX          0.52000
RM           6.40500
AGE         85.40000
DIS          2.71470
RAD          5.00000
TAX        384.00000
PTRATIO     20.90000
B           70.80000
LSTAT       10.63000
Name: 102, dtype: float64
CRIM         0.97617
ZN           0.00000
INDUS       21.89000
CHAS         0.00000
NOX          0.62400
RM           5.75700
AGE         98.40000
DIS          2.34600
RAD          4.00000
TAX        437.00000
PTRATIO     21.20000
B          262.76000
LSTAT       17.31000
Name: 134, dtype: float64
CRIM         2.37934
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.87100
RM           6.13000
AGE        100.00000
DIS          1.41910
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          172.91000
LSTAT       27.80000
Name: 145, dtype: float64
CRIM         2.15505
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.87100
RM           5.62800
AGE        100.00000
DIS          1.51660
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          169.27000
LSTAT       16.65000
Name: 146, dtype: float64
CRIM         2.14918
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.87100
RM           5.70900
AGE         98.50000
DIS          1.62320
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          261.95000
LSTAT       15.79000
Name: 153, dtype: float64
CRIM         3.53501
ZN           0.00000
INDUS       19.58000
CHAS         1.00000
NOX          0.87100
RM           6.15200
AGE         82.60000
DIS          1.74550
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B           88.01000
LSTAT       15.02000
Name: 155, dtype: float64
CRIM         2.44668
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.87100
RM           5.27200
AGE         94.00000
DIS          1.73640
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B           88.63000
LSTAT       16.14000
Name: 156, dtype: float64
CRIM         2.9240
ZN           0.0000
INDUS       19.5800
CHAS         0.0000
NOX          0.6050
RM           6.1010
AGE         93.0000
DIS          2.2834
RAD          5.0000
TAX        403.0000
PTRATIO     14.7000
B          240.1600
LSTAT        9.8100
Name: 165, dtype: float64
CRIM         1.80028
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.60500
RM           5.87700
AGE         79.20000
DIS          2.42590
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          227.61000
LSTAT       12.14000
Name: 167, dtype: float64
Cluster  8
CRIM         0.02763
ZN          75.00000
INDUS        2.95000
CHAS         0.00000
NOX          0.42800
RM           6.59500
AGE         21.80000
DIS          5.40110
RAD          3.00000
TAX        252.00000
PTRATIO     18.30000
B          395.63000
LSTAT        4.32000
Name: 39, dtype: float64
CRIM         0.03359
ZN          75.00000
INDUS        2.95000
CHAS         0.00000
NOX          0.42800
RM           7.02400
AGE         15.80000
DIS          5.40110
RAD          3.00000
TAX        252.00000
PTRATIO     18.30000
B          395.62000
LSTAT        1.98000
Name: 40, dtype: float64
CRIM         0.0536
ZN          21.0000
INDUS        5.6400
CHAS         0.0000
NOX          0.4390
RM           6.5110
AGE         21.1000
DIS          6.8147
RAD          4.0000
TAX        243.0000
PTRATIO     16.8000
B          396.9000
LSTAT        5.2800
Name: 52, dtype: float64
CRIM         0.04981
ZN          21.00000
INDUS        5.64000
CHAS         0.00000
NOX          0.43900
RM           5.99800
AGE         21.40000
DIS          6.81470
RAD          4.00000
TAX        243.00000
PTRATIO     16.80000
B          396.90000
LSTAT        8.43000
Name: 53, dtype: float64
CRIM         0.01311
ZN          90.00000
INDUS        1.22000
CHAS         0.00000
NOX          0.40300
RM           7.24900
AGE         21.90000
DIS          8.69660
RAD          5.00000
TAX        226.00000
PTRATIO     17.90000
B          395.93000
LSTAT        4.81000
Name: 55, dtype: float64
CRIM         0.01432
ZN         100.00000
INDUS        1.32000
CHAS         0.00000
NOX          0.41100
RM           6.81600
AGE         40.50000
DIS          8.32480
RAD          5.00000
TAX        256.00000
PTRATIO     15.10000
B          392.90000
LSTAT        3.95000
Name: 57, dtype: float64
CRIM         0.15445
ZN          25.00000
INDUS        5.13000
CHAS         0.00000
NOX          0.45300
RM           6.14500
AGE         29.20000
DIS          7.81480
RAD          8.00000
TAX        284.00000
PTRATIO     19.70000
B          390.68000
LSTAT        6.86000
Name: 58, dtype: float64
CRIM         0.04113
ZN          25.00000
INDUS        4.86000
CHAS         0.00000
NOX          0.42600
RM           6.72700
AGE         33.50000
DIS          5.40070
RAD          4.00000
TAX        281.00000
PTRATIO     19.00000
B          396.90000
LSTAT        5.29000
Name: 80, dtype: float64
CRIM         0.03659
ZN          25.00000
INDUS        4.86000
CHAS         0.00000
NOX          0.42600
RM           6.30200
AGE         32.20000
DIS          5.40070
RAD          4.00000
TAX        281.00000
PTRATIO     19.00000
B          396.90000
LSTAT        6.72000
Name: 82, dtype: float64
CRIM         0.02875
ZN          28.00000
INDUS       15.04000
CHAS         0.00000
NOX          0.46400
RM           6.21100
AGE         28.90000
DIS          3.66590
RAD          4.00000
TAX        270.00000
PTRATIO     18.20000
B          396.33000
LSTAT        6.21000
Name: 93, dtype: float64
CRIM         0.02187
ZN          60.00000
INDUS        2.93000
CHAS         0.00000
NOX          0.40100
RM           6.80000
AGE          9.90000
DIS          6.21960
RAD          1.00000
TAX        265.00000
PTRATIO     15.60000
B          393.37000
LSTAT        5.03000
Name: 193, dtype: float64
CRIM         0.01439
ZN          60.00000
INDUS        2.93000
CHAS         0.00000
NOX          0.40100
RM           6.60400
AGE         18.80000
DIS          6.21960
RAD          1.00000
TAX        265.00000
PTRATIO     15.60000
B          376.70000
LSTAT        4.38000
Name: 194, dtype: float64
CRIM         0.01381
ZN          80.00000
INDUS        0.46000
CHAS         0.00000
NOX          0.42200
RM           7.87500
AGE         32.00000
DIS          5.64840
RAD          4.00000
TAX        255.00000
PTRATIO     14.40000
B          394.23000
LSTAT        2.97000
Name: 195, dtype: float64
CRIM         0.0351
ZN          95.0000
INDUS        2.6800
CHAS         0.0000
NOX          0.4161
RM           7.8530
AGE         33.2000
DIS          5.1180
RAD          4.0000
TAX        224.0000
PTRATIO     14.7000
B          392.7800
LSTAT        3.8100
Name: 203, dtype: float64
CRIM         0.02009
ZN          95.00000
INDUS        2.68000
CHAS         0.00000
NOX          0.41610
RM           8.03400
AGE         31.90000
DIS          5.11800
RAD          4.00000
TAX        224.00000
PTRATIO     14.70000
B          390.55000
LSTAT        2.88000
Name: 204, dtype: float64
CRIM         0.08244
ZN          30.00000
INDUS        4.93000
CHAS         0.00000
NOX          0.42800
RM           6.48100
AGE         18.50000
DIS          6.18990
RAD          6.00000
TAX        300.00000
PTRATIO     16.60000
B          379.41000
LSTAT        6.36000
Name: 238, dtype: float64
CRIM         0.12757
ZN          30.00000
INDUS        4.93000
CHAS         0.00000
NOX          0.42800
RM           6.39300
AGE          7.80000
DIS          7.03550
RAD          6.00000
TAX        300.00000
PTRATIO     16.60000
B          374.71000
LSTAT        5.19000
Name: 243, dtype: float64
CRIM         0.01538
ZN          90.00000
INDUS        3.75000
CHAS         0.00000
NOX          0.39400
RM           7.45400
AGE         34.20000
DIS          6.33610
RAD          3.00000
TAX        244.00000
PTRATIO     15.90000
B          386.34000
LSTAT        3.11000
Name: 256, dtype: float64
CRIM         0.05644
ZN          40.00000
INDUS        6.41000
CHAS         1.00000
NOX          0.44700
RM           6.75800
AGE         32.90000
DIS          4.07760
RAD          4.00000
TAX        254.00000
PTRATIO     17.60000
B          396.90000
LSTAT        3.53000
Name: 274, dtype: float64
CRIM         0.09604
ZN          40.00000
INDUS        6.41000
CHAS         0.00000
NOX          0.44700
RM           6.85400
AGE         42.80000
DIS          4.26730
RAD          4.00000
TAX        254.00000
PTRATIO     17.60000
B          396.90000
LSTAT        2.98000
Name: 275, dtype: float64
CRIM         0.10469
ZN          40.00000
INDUS        6.41000
CHAS         1.00000
NOX          0.44700
RM           7.26700
AGE         49.00000
DIS          4.78720
RAD          4.00000
TAX        254.00000
PTRATIO     17.60000
B          389.25000
LSTAT        6.05000
Name: 276, dtype: float64
CRIM         0.06127
ZN          40.00000
INDUS        6.41000
CHAS         1.00000
NOX          0.44700
RM           6.82600
AGE         27.60000
DIS          4.86280
RAD          4.00000
TAX        254.00000
PTRATIO     17.60000
B          393.45000
LSTAT        4.16000
Name: 277, dtype: float64
CRIM         0.07978
ZN          40.00000
INDUS        6.41000
CHAS         0.00000
NOX          0.44700
RM           6.48200
AGE         32.10000
DIS          4.14030
RAD          4.00000
TAX        254.00000
PTRATIO     17.60000
B          396.90000
LSTAT        7.19000
Name: 278, dtype: float64
CRIM         0.01501
ZN          90.00000
INDUS        1.21000
CHAS         1.00000
NOX          0.40100
RM           7.92300
AGE         24.80000
DIS          5.88500
RAD          1.00000
TAX        198.00000
PTRATIO     13.60000
B          395.52000
LSTAT        3.16000
Name: 283, dtype: float64
CRIM         0.00906
ZN          90.00000
INDUS        2.97000
CHAS         0.00000
NOX          0.40000
RM           7.08800
AGE         20.80000
DIS          7.30730
RAD          1.00000
TAX        285.00000
PTRATIO     15.30000
B          394.72000
LSTAT        7.85000
Name: 284, dtype: float64
CRIM         0.01096
ZN          55.00000
INDUS        2.25000
CHAS         0.00000
NOX          0.38900
RM           6.45300
AGE         31.90000
DIS          7.30730
RAD          1.00000
TAX        300.00000
PTRATIO     15.30000
B          394.72000
LSTAT        8.23000
Name: 285, dtype: float64
CRIM         0.01965
ZN          80.00000
INDUS        1.76000
CHAS         0.00000
NOX          0.38500
RM           6.23000
AGE         31.50000
DIS          9.08920
RAD          1.00000
TAX        241.00000
PTRATIO     18.20000
B          341.60000
LSTAT       12.93000
Name: 286, dtype: float64
CRIM         0.03871
ZN          52.50000
INDUS        5.32000
CHAS         0.00000
NOX          0.40500
RM           6.20900
AGE         31.30000
DIS          7.31720
RAD          6.00000
TAX        293.00000
PTRATIO     16.60000
B          396.90000
LSTAT        7.14000
Name: 287, dtype: float64
CRIM         0.0459
ZN          52.5000
INDUS        5.3200
CHAS         0.0000
NOX          0.4050
RM           6.3150
AGE         45.6000
DIS          7.3172
RAD          6.0000
TAX        293.0000
PTRATIO     16.6000
B          396.9000
LSTAT        7.6000
Name: 288, dtype: float64
CRIM         0.04297
ZN          52.50000
INDUS        5.32000
CHAS         0.00000
NOX          0.40500
RM           6.56500
AGE         22.90000
DIS          7.31720
RAD          6.00000
TAX        293.00000
PTRATIO     16.60000
B          371.72000
LSTAT        9.51000
Name: 289, dtype: float64
CRIM         0.03502
ZN          80.00000
INDUS        4.95000
CHAS         0.00000
NOX          0.41100
RM           6.86100
AGE         27.90000
DIS          5.11670
RAD          4.00000
TAX        245.00000
PTRATIO     19.20000
B          396.90000
LSTAT        3.33000
Name: 290, dtype: float64
CRIM         0.07886
ZN          80.00000
INDUS        4.95000
CHAS         0.00000
NOX          0.41100
RM           7.14800
AGE         27.70000
DIS          5.11670
RAD          4.00000
TAX        245.00000
PTRATIO     19.20000
B          396.90000
LSTAT        3.56000
Name: 291, dtype: float64
CRIM         0.03615
ZN          80.00000
INDUS        4.95000
CHAS         0.00000
NOX          0.41100
RM           6.63000
AGE         23.40000
DIS          5.11670
RAD          4.00000
TAX        245.00000
PTRATIO     19.20000
B          396.90000
LSTAT        4.70000
Name: 292, dtype: float64
CRIM         0.05023
ZN          35.00000
INDUS        6.06000
CHAS         0.00000
NOX          0.43790
RM           5.70600
AGE         28.40000
DIS          6.64070
RAD          1.00000
TAX        304.00000
PTRATIO     16.90000
B          394.02000
LSTAT       12.43000
Name: 331, dtype: float64
CRIM         0.03466
ZN          35.00000
INDUS        6.06000
CHAS         0.00000
NOX          0.43790
RM           6.03100
AGE         23.30000
DIS          6.64070
RAD          1.00000
TAX        304.00000
PTRATIO     16.90000
B          362.25000
LSTAT        7.83000
Name: 332, dtype: float64
CRIM         0.01501
ZN          80.00000
INDUS        2.01000
CHAS         0.00000
NOX          0.43500
RM           6.63500
AGE         29.70000
DIS          8.34400
RAD          4.00000
TAX        280.00000
PTRATIO     17.00000
B          390.94000
LSTAT        5.99000
Name: 348, dtype: float64
CRIM         0.01709
ZN          90.00000
INDUS        2.02000
CHAS         0.00000
NOX          0.41000
RM           6.72800
AGE         36.10000
DIS         12.12650
RAD          5.00000
TAX        187.00000
PTRATIO     17.00000
B          384.46000
LSTAT        4.50000
Name: 353, dtype: float64
Cluster  3
CRIM         0.0136
ZN          75.0000
INDUS        4.0000
CHAS         0.0000
NOX          0.4100
RM           5.8880
AGE         47.6000
DIS          7.3197
RAD          3.0000
TAX        469.0000
PTRATIO     21.1000
B          396.9000
LSTAT       14.8000

Name: 116, dtype: float64
CRIM         0.15098
ZN           0.00000
INDUS       10.01000
CHAS         0.00000
NOX          0.54700
RM           6.02100
AGE         82.60000
DIS          2.74740
RAD          6.00000
TAX        432.00000
PTRATIO     17.80000
B          394.51000
LSTAT       10.30000
Name: 117, dtype: float64
CRIM         0.13058
ZN           0.00000
INDUS       10.01000
CHAS         0.00000
NOX          0.54700
RM           5.87200
AGE         73.10000
DIS          2.47750
RAD          6.00000
TAX        432.00000
PTRATIO     17.80000
B          338.63000
LSTAT       15.37000
Name: 118, dtype: float64
CRIM         0.14476
ZN           0.00000
INDUS       10.01000
CHAS         0.00000
NOX          0.54700
RM           5.73100
AGE         65.20000
DIS          2.75920
RAD          6.00000
TAX        432.00000
PTRATIO     17.80000
B          391.50000
LSTAT       13.61000
Name: 119, dtype: float64
CRIM         0.25915
ZN           0.00000
INDUS       21.89000
CHAS         0.00000
NOX          0.62400
RM           5.69300
AGE         96.00000
DIS          1.78830
RAD          4.00000
TAX        437.00000
PTRATIO     21.20000
B          392.11000
LSTAT       17.19000
Name: 127, dtype: float64
CRIM         0.32543
ZN           0.00000
INDUS       21.89000
CHAS         0.00000
NOX          0.62400
RM           6.43100
AGE         98.80000
DIS          1.81250
RAD          4.00000
TAX        437.00000
PTRATIO     21.20000
B          396.90000
LSTAT       15.39000
Name: 128, dtype: float64
CRIM         0.88125
ZN           0.00000
INDUS       21.89000
CHAS         0.00000
NOX          0.62400
RM           5.63700
AGE         94.70000
DIS          1.97990
RAD          4.00000
TAX        437.00000
PTRATIO     21.20000
B          396.90000
LSTAT       18.34000
Name: 129, dtype: float64
CRIM         0.34006
ZN           0.00000
INDUS       21.89000
CHAS         0.00000
NOX          0.62400
RM           6.45800
AGE         98.90000
DIS          2.11850
RAD          4.00000
TAX        437.00000
PTRATIO     21.20000
B          395.04000
LSTAT       12.60000
Name: 130, dtype: float64
CRIM         1.19294
ZN           0.00000
INDUS       21.89000
CHAS         0.00000
NOX          0.62400
RM           6.32600
AGE         97.70000
DIS          2.27100
RAD          4.00000
TAX        437.00000
PTRATIO     21.20000
B          396.90000
LSTAT       12.26000
Name: 131, dtype: float64
CRIM         0.59005
ZN           0.00000
INDUS       21.89000
CHAS         0.00000
NOX          0.62400
RM           6.37200
AGE         97.90000
DIS          2.32740
RAD          4.00000
TAX        437.00000
PTRATIO     21.20000
B          385.76000
LSTAT       11.12000
Name: 132, dtype: float64
CRIM         0.32982
ZN           0.00000
INDUS       21.89000
CHAS         0.00000
NOX          0.62400
RM           5.82200
AGE         95.40000
DIS          2.46990
RAD          4.00000
TAX        437.00000
PTRATIO     21.20000
B          388.69000
LSTAT       15.03000
Name: 133, dtype: float64
CRIM         0.55778
ZN           0.00000
INDUS       21.89000
CHAS         0.00000
NOX          0.62400
RM           6.33500
AGE         98.20000
DIS          2.11070
RAD          4.00000
TAX        437.00000
PTRATIO     21.20000
B          394.67000
LSTAT       16.96000
Name: 135, dtype: float64
CRIM         0.32264
ZN           0.00000
INDUS       21.89000
CHAS         0.00000
NOX          0.62400
RM           5.94200
AGE         93.50000
DIS          1.96690
RAD          4.00000
TAX        437.00000
PTRATIO     21.20000
B          378.25000
LSTAT       16.90000
Name: 136, dtype: float64
CRIM         0.35233
ZN           0.00000
INDUS       21.89000
CHAS         0.00000
NOX          0.62400
RM           6.45400
AGE         98.40000
DIS          1.84980
RAD          4.00000
TAX        437.00000
PTRATIO     21.20000
B          394.08000
LSTAT       14.59000
Name: 137, dtype: float64
CRIM         0.2498
ZN           0.0000
INDUS       21.8900
CHAS         0.0000
NOX          0.6240
RM           5.8570
AGE         98.2000
DIS          1.6686
RAD          4.0000
TAX        437.0000
PTRATIO     21.2000
B          392.0400
LSTAT       21.3200
Name: 138, dtype: float64
CRIM         0.54452
ZN           0.00000
INDUS       21.89000
CHAS         0.00000
NOX          0.62400
RM           6.15100
AGE         97.90000
DIS          1.66870
RAD          4.00000
TAX        437.00000
PTRATIO     21.20000
B          396.90000
LSTAT       18.46000
Name: 139, dtype: float64
CRIM         0.2909
ZN           0.0000
INDUS       21.8900
CHAS         0.0000
NOX          0.6240
RM           6.1740
AGE         93.6000
DIS          1.6119
RAD          4.0000
TAX        437.0000
PTRATIO     21.2000
B          388.0800
LSTAT       24.1600
Name: 140, dtype: float64
CRIM         1.62864
ZN           0.00000
INDUS       21.89000
CHAS         0.00000
NOX          0.62400
RM           5.01900
AGE        100.00000
DIS          1.43940
RAD          4.00000
TAX        437.00000
PTRATIO     21.20000
B          396.90000
LSTAT       34.41000
Name: 141, dtype: float64
CRIM         3.32105
ZN           0.00000
INDUS       19.58000
CHAS         1.00000
NOX          0.87100
RM           5.40300
AGE        100.00000
DIS          1.32160
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          396.90000
LSTAT       26.82000
Name: 142, dtype: float64
CRIM         4.0974
ZN           0.0000
INDUS       19.5800
CHAS         0.0000
NOX          0.8710
RM           5.4680
AGE        100.0000
DIS          1.4118
RAD          5.0000
TAX        403.0000
PTRATIO     14.7000
B          396.9000
LSTAT       26.4200
Name: 143, dtype: float64
CRIM         2.77974
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.87100
RM           4.90300
AGE         97.80000
DIS          1.34590
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          396.90000
LSTAT       29.29000
Name: 144, dtype: float64
CRIM         2.36862
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.87100
RM           4.92600
AGE         95.70000
DIS          1.46080
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          391.71000
LSTAT       29.53000
Name: 147, dtype: float64
CRIM         2.33099
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.87100
RM           5.18600
AGE         93.80000
DIS          1.52960
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          356.99000
LSTAT       28.32000
Name: 148, dtype: float64
CRIM         2.73397
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.87100
RM           5.59700
AGE         94.90000
DIS          1.52570
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          351.85000
LSTAT       21.45000
Name: 149, dtype: float64
CRIM         1.6566
ZN           0.0000
INDUS       19.5800
CHAS         0.0000
NOX          0.8710
RM           6.1220
AGE         97.3000
DIS          1.6180
RAD          5.0000
TAX        403.0000
PTRATIO     14.7000
B          372.8000
LSTAT       14.1000
Name: 150, dtype: float64
CRIM         1.49632
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.87100
RM           5.40400
AGE        100.00000
DIS          1.59160
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          341.60000
LSTAT       13.28000
Name: 151, dtype: float64
CRIM         1.12658
ZN           0.00000
INDUS       19.58000
CHAS         1.00000
NOX          0.87100
RM           5.01200
AGE         88.00000
DIS          1.61020
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          343.28000
LSTAT       12.12000
Name: 152, dtype: float64
CRIM         1.41385
ZN           0.00000
INDUS       19.58000
CHAS         1.00000
NOX          0.87100
RM           6.12900
AGE         96.00000
DIS          1.74940
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          321.02000
LSTAT       15.12000
Name: 154, dtype: float64
CRIM         1.22358
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.60500
RM           6.94300
AGE         97.40000
DIS          1.87730
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          363.43000
LSTAT        4.59000
Name: 157, dtype: float64
CRIM         1.34284
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.60500
RM           6.06600
AGE        100.00000
DIS          1.75730
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          353.89000
LSTAT        6.43000
Name: 158, dtype: float64
CRIM         1.42502
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.87100
RM           6.51000
AGE        100.00000
DIS          1.76590
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          364.31000
LSTAT        7.39000
Name: 159, dtype: float64
CRIM         1.27346
ZN           0.00000
INDUS       19.58000
CHAS         1.00000
NOX          0.60500
RM           6.25000
AGE         92.60000
DIS          1.79840
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          338.92000
LSTAT        5.50000
Name: 160, dtype: float64
CRIM         1.46336
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.60500
RM           7.48900
AGE         90.80000
DIS          1.97090
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          374.43000
LSTAT        1.73000
Name: 161, dtype: float64
CRIM         1.83377
ZN           0.00000
INDUS       19.58000
CHAS         1.00000
NOX          0.60500
RM           7.80200
AGE         98.20000
DIS          2.04070
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          389.61000
LSTAT        1.92000
Name: 162, dtype: float64
CRIM         1.51902
ZN           0.00000
INDUS       19.58000
CHAS         1.00000
NOX          0.60500
RM           8.37500
AGE         93.90000
DIS          2.16200
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          388.45000
LSTAT        3.32000
Name: 163, dtype: float64
CRIM         2.24236
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.60500
RM           5.85400
AGE         91.80000
DIS          2.42200
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          395.11000
LSTAT       11.64000
Name: 164, dtype: float64
CRIM         2.01019
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.60500
RM           7.92900
AGE         96.20000
DIS          2.04590
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          369.30000
LSTAT        3.70000
Name: 166, dtype: float64
CRIM         2.3004
ZN           0.0000
INDUS       19.5800
CHAS         0.0000
NOX          0.6050
RM           6.3190
AGE         96.1000
DIS          2.1000
RAD          5.0000
TAX        403.0000
PTRATIO     14.7000
B          297.0900
LSTAT       11.1000
Name: 168, dtype: float64
CRIM         2.44953
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.60500
RM           6.40200
AGE         95.20000
DIS          2.26250
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          330.04000
LSTAT       11.32000
Name: 169, dtype: float64
CRIM         1.20742
ZN           0.00000
INDUS       19.58000
CHAS         0.00000
NOX          0.60500
RM           5.87500
AGE         94.60000
DIS          2.42590
RAD          5.00000
TAX        403.00000
PTRATIO     14.70000
B          292.29000
LSTAT       14.43000
Name: 170, dtype: float64
CRIM         2.3139
ZN           0.0000
INDUS       19.5800
CHAS         0.0000
NOX          0.6050
RM           5.8800
AGE         97.3000
DIS          2.3887
RAD          5.0000
TAX        403.0000
PTRATIO     14.7000
B          348.1300
LSTAT       12.0300
Name: 171, dtype: float64
CRIM         0.06617
ZN           0.00000
INDUS        3.24000
CHAS         0.00000
NOX          0.46000
RM           5.86800
AGE         25.80000
DIS          5.21460
RAD          4.00000
TAX        430.00000
PTRATIO     16.90000
B          382.44000
LSTAT        9.97000
Name: 328, dtype: float64
CRIM         0.06724
ZN           0.00000
INDUS        3.24000
CHAS         0.00000
NOX          0.46000
RM           6.33300
AGE         17.20000
DIS          5.21460
RAD          4.00000
TAX        430.00000
PTRATIO     16.90000
B          375.21000
LSTAT        7.34000
Name: 329, dtype: float64
CRIM         0.04544
ZN           0.00000
INDUS        3.24000
CHAS         0.00000
NOX          0.46000
RM           6.14400
AGE         32.20000
DIS          5.87360
RAD          4.00000
TAX        430.00000
PTRATIO     16.90000
B          368.57000
LSTAT        9.09000
Name: 330, dtype: float64
CRIM         0.02498
ZN           0.00000
INDUS        1.89000
CHAS         0.00000
NOX          0.51800
RM           6.54000
AGE         59.70000
DIS          6.26690
RAD          1.00000
TAX        422.00000
PTRATIO     15.90000
B          389.96000
LSTAT        8.65000
Name: 342, dtype: float64
CRIM         0.17331
ZN           0.00000
INDUS        9.69000
CHAS         0.00000
NOX          0.58500
RM           5.70700
AGE         54.00000
DIS          2.38170
RAD          6.00000
TAX        391.00000
PTRATIO     19.20000
B          396.90000
LSTAT       12.01000
Name: 493, dtype: float64
CRIM         0.27957
ZN           0.00000
INDUS        9.69000
CHAS         0.00000
NOX          0.58500
RM           5.92600
AGE         42.60000
DIS          2.38170
RAD          6.00000
TAX        391.00000
PTRATIO     19.20000
B          396.90000
LSTAT       13.59000
Name: 494, dtype: float64
CRIM         0.17899
ZN           0.00000
INDUS        9.69000
CHAS         0.00000
NOX          0.58500
RM           5.67000
AGE         28.80000
DIS          2.79860
RAD          6.00000
TAX        391.00000
PTRATIO     19.20000
B          393.29000
LSTAT       17.60000
Name: 495, dtype: float64
CRIM         0.2896
ZN           0.0000
INDUS        9.6900
CHAS         0.0000
NOX          0.5850
RM           5.3900
AGE         72.9000
DIS          2.7986
RAD          6.0000
TAX        391.0000
PTRATIO     19.2000
B          396.9000
LSTAT       21.1400
Name: 496, dtype: float64
CRIM         0.26838
ZN           0.00000
INDUS        9.69000
CHAS         0.00000
NOX          0.58500
RM           5.79400
AGE         70.60000
DIS          2.89270
RAD          6.00000
TAX        391.00000
PTRATIO     19.20000
B          396.90000
LSTAT       14.10000
Name: 497, dtype: float64
CRIM         0.23912
ZN           0.00000
INDUS        9.69000
CHAS         0.00000
NOX          0.58500
RM           6.01900
AGE         65.30000
DIS          2.40910
RAD          6.00000
TAX        391.00000
PTRATIO     19.20000
B          396.90000
LSTAT       12.92000
Name: 498, dtype: float64
CRIM         0.17783
ZN           0.00000
INDUS        9.69000
CHAS         0.00000
NOX          0.58500
RM           5.56900
AGE         73.50000
DIS          2.39990
RAD          6.00000
TAX        391.00000
PTRATIO     19.20000
B          395.77000
LSTAT       15.10000
Name: 499, dtype: float64
CRIM         0.22438
ZN           0.00000
INDUS        9.69000
CHAS         0.00000
NOX          0.58500
RM           6.02700
AGE         79.70000
DIS          2.49820
RAD          6.00000
TAX        391.00000
PTRATIO     19.20000
B          396.90000
LSTAT       14.33000
Name: 500, dtype: float64
Cluster  7
CRIM         0.02055
ZN          85.00000
INDUS        0.74000
CHAS         0.00000
NOX          0.41000
RM           6.38300
AGE         35.70000
DIS          9.18760
RAD          2.00000
TAX        313.00000
PTRATIO     17.30000
B          396.90000
LSTAT        5.77000
Name: 56, dtype: float64
CRIM         0.03584
ZN          80.00000
INDUS        3.37000
CHAS         0.00000
NOX          0.39800
RM           6.29000
AGE         17.80000
DIS          6.61150
RAD          4.00000
TAX        337.00000
PTRATIO     16.10000
B          396.90000
LSTAT        4.67000
Name: 65, dtype: float64
CRIM         0.04379
ZN          80.00000
INDUS        3.37000
CHAS         0.00000
NOX          0.39800
RM           5.78700
AGE         31.10000
DIS          6.61150
RAD          4.00000
TAX        337.00000
PTRATIO     16.10000
B          396.90000
LSTAT       10.24000
Name: 66, dtype: float64
CRIM         0.05789
ZN          12.50000
INDUS        6.07000
CHAS         0.00000
NOX          0.40900
RM           5.87800
AGE         21.40000
DIS          6.49800
RAD          4.00000
TAX        345.00000
PTRATIO     18.90000
B          396.21000
LSTAT        8.10000
Name: 67, dtype: float64
CRIM         0.13554
ZN          12.50000
INDUS        6.07000
CHAS         0.00000
NOX          0.40900
RM           5.59400
AGE         36.80000
DIS          6.49800
RAD          4.00000
TAX        345.00000
PTRATIO     18.90000
B          396.90000
LSTAT       13.09000
Name: 68, dtype: float64
CRIM         0.12816
ZN          12.50000
INDUS        6.07000
CHAS         0.00000
NOX          0.40900
RM           5.88500
AGE         33.00000
DIS          6.49800
RAD          4.00000
TAX        345.00000
PTRATIO     18.90000
B          396.90000
LSTAT        8.79000
Name: 69, dtype: float64
CRIM         0.07896
ZN           0.00000
INDUS       12.83000
CHAS         0.00000
NOX          0.43700
RM           6.27300
AGE          6.00000
DIS          4.25150
RAD          5.00000
TAX        398.00000
PTRATIO     18.70000
B          394.92000
LSTAT        6.78000
Name: 74, dtype: float64
CRIM         0.07875
ZN          45.00000
INDUS        3.44000
CHAS         0.00000
NOX          0.43700
RM           6.78200
AGE         41.10000
DIS          3.78860
RAD          5.00000
TAX        398.00000
PTRATIO     15.20000
B          393.87000
LSTAT        6.68000
Name: 187, dtype: float64
CRIM         0.12579
ZN          45.00000
INDUS        3.44000
CHAS         0.00000
NOX          0.43700
RM           6.55600
AGE         29.10000
DIS          4.56670
RAD          5.00000
TAX        398.00000
PTRATIO     15.20000
B          382.84000
LSTAT        4.56000
Name: 188, dtype: float64
CRIM         0.0837
ZN          45.0000
INDUS        3.4400
CHAS         0.0000
NOX          0.4370
RM           7.1850
AGE         38.9000
DIS          4.5667
RAD          5.0000
TAX        398.0000
PTRATIO     15.2000
B          396.9000
LSTAT        5.3900
Name: 189, dtype: float64
CRIM         0.09068
ZN          45.00000
INDUS        3.44000
CHAS         0.00000
NOX          0.43700
RM           6.95100
AGE         21.50000
DIS          6.47980
RAD          5.00000
TAX        398.00000
PTRATIO     15.20000
B          377.68000
LSTAT        5.10000

Name: 190, dtype: float64
CRIM         0.06911
ZN          45.00000
INDUS        3.44000
CHAS         0.00000
NOX          0.43700
RM           6.73900
AGE         30.80000
DIS          6.47980
RAD          5.00000
TAX        398.00000
PTRATIO     15.20000
B          389.71000
LSTAT        4.69000
Name: 191, dtype: float64
CRIM         0.08664
ZN          45.00000
INDUS        3.44000
CHAS         0.00000
NOX          0.43700
RM           7.17800
AGE         26.30000
DIS          6.47980
RAD          5.00000
TAX        398.00000
PTRATIO     15.20000
B          390.49000
LSTAT        2.87000
Name: 192, dtype: float64
CRIM         0.04011
ZN          80.00000
INDUS        1.52000
CHAS         0.00000
NOX          0.40400
RM           7.28700
AGE         34.10000
DIS          7.30900
RAD          2.00000
TAX        329.00000
PTRATIO     12.60000
B          396.90000
LSTAT        4.08000
Name: 196, dtype: float64
CRIM         0.04666
ZN          80.00000
INDUS        1.52000
CHAS         0.00000
NOX          0.40400
RM           7.10700
AGE         36.60000
DIS          7.30900
RAD          2.00000
TAX        329.00000
PTRATIO     12.60000
B          354.31000
LSTAT        8.61000
Name: 197, dtype: float64
CRIM         0.03768
ZN          80.00000
INDUS        1.52000
CHAS         0.00000
NOX          0.40400
RM           7.27400
AGE         38.30000
DIS          7.30900
RAD          2.00000
TAX        329.00000
PTRATIO     12.60000
B          392.20000
LSTAT        6.62000
Name: 198, dtype: float64
CRIM         0.0315
ZN          95.0000
INDUS        1.4700
CHAS         0.0000
NOX          0.4030
RM           6.9750
AGE         15.3000
DIS          7.6534
RAD          3.0000
TAX        402.0000
PTRATIO     17.0000
B          396.9000
LSTAT        4.5600
Name: 199, dtype: float64
CRIM         0.01778
ZN          95.00000
INDUS        1.47000
CHAS         0.00000
NOX          0.40300
RM           7.13500
AGE         13.90000
DIS          7.65340
RAD          3.00000
TAX        402.00000
PTRATIO     17.00000
B          384.30000
LSTAT        4.45000
Name: 200, dtype: float64
CRIM         0.03445
ZN          82.50000
INDUS        2.03000
CHAS         0.00000
NOX          0.41500
RM           6.16200
AGE         38.40000
DIS          6.27000
RAD          2.00000
TAX        348.00000
PTRATIO     14.70000
B          393.77000
LSTAT        7.43000
Name: 201, dtype: float64
CRIM         0.02177
ZN          82.50000
INDUS        2.03000
CHAS         0.00000
NOX          0.41500
RM           7.61000
AGE         15.70000
DIS          6.27000
RAD          2.00000
TAX        348.00000
PTRATIO     14.70000
B          395.38000
LSTAT        3.11000
Name: 202, dtype: float64
CRIM         0.33983
ZN          22.00000
INDUS        5.86000
CHAS         0.00000
NOX          0.43100
RM           6.10800
AGE         34.90000
DIS          8.05550
RAD          7.00000
TAX        330.00000
PTRATIO     19.10000
B          390.18000
LSTAT        9.16000
Name: 246, dtype: float64
CRIM         0.16439
ZN          22.00000
INDUS        5.86000
CHAS         0.00000
NOX          0.43100
RM           6.43300
AGE         49.10000
DIS          7.82650
RAD          7.00000
TAX        330.00000
PTRATIO     19.10000
B          374.71000
LSTAT        9.52000
Name: 248, dtype: float64
CRIM         0.19073
ZN          22.00000
INDUS        5.86000
CHAS         0.00000
NOX          0.43100
RM           6.71800
AGE         17.50000
DIS          7.82650
RAD          7.00000
TAX        330.00000
PTRATIO     19.10000
B          393.74000
LSTAT        6.56000
Name: 249, dtype: float64
CRIM         0.1403
ZN          22.0000
INDUS        5.8600
CHAS         0.0000
NOX          0.4310
RM           6.4870
AGE         13.0000
DIS          7.3967
RAD          7.0000
TAX        330.0000
PTRATIO     19.1000
B          396.2800
LSTAT        5.9000
Name: 250, dtype: float64
CRIM         0.21409
ZN          22.00000
INDUS        5.86000
CHAS         0.00000
NOX          0.43100
RM           6.43800
AGE          8.90000
DIS          7.39670
RAD          7.00000
TAX        330.00000
PTRATIO     19.10000
B          377.07000
LSTAT        3.59000
Name: 251, dtype: float64
CRIM         0.08221
ZN          22.00000
INDUS        5.86000
CHAS         0.00000
NOX          0.43100
RM           6.95700
AGE          6.80000
DIS          8.90670
RAD          7.00000
TAX        330.00000
PTRATIO     19.10000
B          386.09000
LSTAT        3.53000
Name: 252, dtype: float64
CRIM         0.36894
ZN          22.00000
INDUS        5.86000
CHAS         0.00000
NOX          0.43100
RM           8.25900
AGE          8.40000
DIS          8.90670
RAD          7.00000
TAX        330.00000
PTRATIO     19.10000
B          396.90000
LSTAT        3.54000
Name: 253, dtype: float64
CRIM         0.04819
ZN          80.00000
INDUS        3.64000
CHAS         0.00000
NOX          0.39200
RM           6.10800
AGE         32.00000
DIS          9.22030
RAD          1.00000
TAX        315.00000
PTRATIO     16.40000
B          392.89000
LSTAT        6.57000
Name: 254, dtype: float64
CRIM         0.03548
ZN          80.00000
INDUS        3.64000
CHAS         0.00000
NOX          0.39200
RM           5.87600
AGE         19.10000
DIS          9.22030
RAD          1.00000
TAX        315.00000
PTRATIO     16.40000
B          395.18000
LSTAT        9.25000
Name: 255, dtype: float64
CRIM         0.06466
ZN          70.00000
INDUS        2.24000
CHAS         0.00000
NOX          0.40000
RM           6.34500
AGE         20.10000
DIS          7.82780
RAD          5.00000
TAX        358.00000
PTRATIO     14.80000
B          368.24000
LSTAT        4.97000
Name: 298, dtype: float64
CRIM         0.05561
ZN          70.00000
INDUS        2.24000
CHAS         0.00000
NOX          0.40000
RM           7.04100
AGE         10.00000
DIS          7.82780
RAD          5.00000
TAX        358.00000
PTRATIO     14.80000
B          371.58000
LSTAT        4.74000
Name: 299, dtype: float64
CRIM         0.04417
ZN          70.00000
INDUS        2.24000
CHAS         0.00000
NOX          0.40000
RM           6.87100
AGE         47.40000
DIS          7.82780
RAD          5.00000
TAX        358.00000
PTRATIO     14.80000
B          390.86000
LSTAT        6.07000
Name: 300, dtype: float64
CRIM         0.03537
ZN          34.00000
INDUS        6.09000
CHAS         0.00000
NOX          0.43300
RM           6.59000
AGE         40.40000
DIS          5.49170
RAD          7.00000
TAX        329.00000
PTRATIO     16.10000
B          395.75000
LSTAT        9.50000
Name: 301, dtype: float64
CRIM         0.09266
ZN          34.00000
INDUS        6.09000
CHAS         0.00000
NOX          0.43300
RM           6.49500
AGE         18.40000
DIS          5.49170
RAD          7.00000
TAX        329.00000
PTRATIO     16.10000
B          383.61000
LSTAT        8.67000
Name: 302, dtype: float64
CRIM         0.1000
ZN          34.0000
INDUS        6.0900
CHAS         0.0000
NOX          0.4330
RM           6.9820
AGE         17.7000
DIS          5.4917
RAD          7.0000
TAX        329.0000
PTRATIO     16.1000
B          390.4300
LSTAT        4.8600
Name: 303, dtype: float64
CRIM         0.02543
ZN          55.00000
INDUS        3.78000
CHAS         0.00000
NOX          0.48400
RM           6.69600
AGE         56.40000
DIS          5.73210
RAD          5.00000
TAX        370.00000
PTRATIO     17.60000
B          396.90000
LSTAT        7.18000
Name: 343, dtype: float64
CRIM         0.03049
ZN          55.00000
INDUS        3.78000
CHAS         0.00000
NOX          0.48400
RM           6.87400
AGE         28.10000
DIS          6.46540
RAD          5.00000
TAX        370.00000
PTRATIO     17.60000
B          387.97000
LSTAT        4.61000
Name: 344, dtype: float64
CRIM         0.03113
ZN           0.00000
INDUS        4.39000
CHAS         0.00000
NOX          0.44200
RM           6.01400
AGE         48.50000
DIS          8.01360
RAD          3.00000
TAX        352.00000
PTRATIO     18.80000
B          385.64000
LSTAT       10.53000
Name: 345, dtype: float64
CRIM         0.06162
ZN           0.00000
INDUS        4.39000
CHAS         0.00000
NOX          0.44200
RM           5.89800
AGE         52.30000
DIS          8.01360
RAD          3.00000
TAX        352.00000
PTRATIO     18.80000
B          364.61000
LSTAT       12.67000
Name: 346, dtype: float64
CRIM         0.0187
ZN          85.0000
INDUS        4.1500
CHAS         0.0000
NOX          0.4290
RM           6.5160
AGE         27.7000
DIS          8.5353
RAD          4.0000
TAX        351.0000
PTRATIO     17.9000
B          392.4300
LSTAT        6.3600
Name: 347, dtype: float64
CRIM         0.02899
ZN          40.00000
INDUS        1.25000
CHAS         0.00000
NOX          0.42900
RM           6.93900
AGE         34.50000
DIS          8.79210
RAD          1.00000
TAX        335.00000
PTRATIO     19.70000
B          389.85000
LSTAT        5.89000
Name: 349, dtype: float64
CRIM         0.06211
ZN          40.00000
INDUS        1.25000
CHAS         0.00000
NOX          0.42900
RM           6.49000
AGE         44.40000
DIS          8.79210
RAD          1.00000
TAX        335.00000
PTRATIO     19.70000
B          396.90000
LSTAT        5.98000
Name: 350, dtype: float64
CRIM         0.0795
ZN          60.0000
INDUS        1.6900
CHAS         0.0000
NOX          0.4110
RM           6.5790
AGE         35.9000
DIS         10.7103
RAD          4.0000
TAX        411.0000
PTRATIO     18.3000
B          370.7800
LSTAT        5.4900
Name: 351, dtype: float64
CRIM         0.07244
ZN          60.00000
INDUS        1.69000
CHAS         0.00000
NOX          0.41100
RM           5.88400
AGE         18.50000
DIS         10.71030
RAD          4.00000
TAX        411.00000
PTRATIO     18.30000
B          392.33000
LSTAT        7.79000
Name: 352, dtype: float64
CRIM         0.04301
ZN          80.00000
INDUS        1.91000
CHAS         0.00000
NOX          0.41300
RM           5.66300
AGE         21.90000
DIS         10.58570
RAD          4.00000
TAX        334.00000
PTRATIO     22.00000
B          382.80000
LSTAT        8.05000
Name: 354, dtype: float64
CRIM         0.10659
ZN          80.00000
INDUS        1.91000
CHAS         0.00000
NOX          0.41300
RM           5.93600
AGE         19.50000
DIS         10.58570
RAD          4.00000
TAX        334.00000
PTRATIO     22.00000
B          376.04000
LSTAT        5.57000
Name: 355, dtype: float64
Cluster  4
CRIM         8.98296
ZN           0.00000
INDUS       18.10000
CHAS         1.00000
NOX          0.77000
RM           6.21200
AGE         97.40000
DIS          2.12220
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          377.73000
LSTAT       17.60000
Name: 356, dtype: float64
CRIM         3.8497
ZN           0.0000
INDUS       18.1000
CHAS         1.0000
NOX          0.7700
RM           6.3950
AGE         91.0000
DIS          2.5052
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          391.3400
LSTAT       13.2700
Name: 357, dtype: float64
CRIM         5.20177
ZN           0.00000
INDUS       18.10000
CHAS         1.00000
NOX          0.77000
RM           6.12700
AGE         83.40000
DIS          2.72270
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          395.43000
LSTAT       11.48000
Name: 358, dtype: float64
CRIM         4.26131
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.77000
RM           6.11200
AGE         81.30000
DIS          2.50910
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          390.74000
LSTAT       12.67000
Name: 359, dtype: float64
CRIM         4.54192
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.77000
RM           6.39800
AGE         88.00000
DIS          2.51820
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          374.56000
LSTAT        7.79000
Name: 360, dtype: float64
CRIM         3.83684
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.77000
RM           6.25100
AGE         91.10000
DIS          2.29550
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          350.65000
LSTAT       14.19000
Name: 361, dtype: float64
CRIM         3.67822
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.77000
RM           5.36200
AGE         96.20000
DIS          2.10360
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          380.79000
LSTAT       10.19000
Name: 362, dtype: float64
CRIM         4.22239
ZN           0.00000
INDUS       18.10000
CHAS         1.00000
NOX          0.77000
RM           5.80300
AGE         89.00000
DIS          1.90470
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          353.04000
LSTAT       14.64000
Name: 363, dtype: float64
CRIM         3.47428
ZN           0.00000
INDUS       18.10000
CHAS         1.00000
NOX          0.71800
RM           8.78000
AGE         82.90000
DIS          1.90470
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          354.55000
LSTAT        5.29000
Name: 364, dtype: float64
CRIM         4.55587
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71800
RM           3.56100
AGE         87.90000
DIS          1.61320
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          354.70000
LSTAT        7.12000
Name: 365, dtype: float64
CRIM         4.89822
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.63100
RM           4.97000
AGE        100.00000
DIS          1.33250
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          375.52000
LSTAT        3.26000
Name: 368, dtype: float64
CRIM         5.66998
ZN           0.00000
INDUS       18.10000
CHAS         1.00000
NOX          0.63100
RM           6.68300
AGE         96.80000
DIS          1.35670
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          375.33000
LSTAT        3.73000
Name: 369, dtype: float64
CRIM         6.53876
ZN           0.00000
INDUS       18.10000
CHAS         1.00000
NOX          0.63100
RM           7.01600
AGE         97.50000
DIS          1.20240
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          392.05000
LSTAT        2.96000
Name: 370, dtype: float64
CRIM         9.2323
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6310
RM           6.2160
AGE        100.0000
DIS          1.1691
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          366.1500
LSTAT        9.5300
Name: 371, dtype: float64
CRIM         8.26725
ZN           0.00000
INDUS       18.10000
CHAS         1.00000
NOX          0.66800
RM           5.87500
AGE         89.60000
DIS          1.12960
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          347.88000
LSTAT        8.88000
Name: 372, dtype: float64
CRIM        11.1081
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6680
RM           4.9060
AGE        100.0000
DIS          1.1742
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       34.7700
Name: 373, dtype: float64
CRIM        18.4982
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6680
RM           4.1380
AGE        100.0000
DIS          1.1370
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       37.9700
Name: 374, dtype: float64
CRIM        19.6091
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6710
RM           7.3130
AGE         97.9000
DIS          1.3163
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       13.4400
Name: 375, dtype: float64
CRIM        15.2880
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6710
RM           6.6490
AGE         93.3000
DIS          1.3449
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          363.0200
LSTAT       23.2400
Name: 376, dtype: float64
CRIM         9.82349
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.67100
RM           6.79400
AGE         98.80000
DIS          1.35800
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          396.90000
LSTAT       21.24000
Name: 377, dtype: float64
CRIM        23.6482
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6710
RM           6.3800
AGE         96.2000
DIS          1.3861
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       23.6900
Name: 378, dtype: float64
CRIM        17.8667
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6710
RM           6.2230
AGE        100.0000
DIS          1.3861
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          393.7400
LSTAT       21.7800
Name: 379, dtype: float64
CRIM        88.9762
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6710
RM           6.9680
AGE         91.9000
DIS          1.4165
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       17.2100
Name: 380, dtype: float64
CRIM        15.8744
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6710
RM           6.5450
AGE         99.1000
DIS          1.5192
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       21.0800
Name: 381, dtype: float64
CRIM         9.18702
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.70000
RM           5.53600
AGE        100.00000
DIS          1.58040
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          396.90000
LSTAT       23.60000
Name: 382, dtype: float64
CRIM         7.99248
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.70000
RM           5.52000
AGE        100.00000
DIS          1.53310
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          396.90000
LSTAT       24.56000
Name: 383, dtype: float64
CRIM        16.8118
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7000
RM           5.2770
AGE         98.1000
DIS          1.4261
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       30.8100
Name: 385, dtype: float64
CRIM        24.3938
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7000
RM           4.6520
AGE        100.0000
DIS          1.4672
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       28.2800
Name: 386, dtype: float64
CRIM        22.5971
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7000
RM           5.0000
AGE         89.5000
DIS          1.5184
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       31.9900
Name: 387, dtype: float64
CRIM        14.3337
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7000
RM           4.8800
AGE        100.0000
DIS          1.5895
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          372.9200
LSTAT       30.6200
Name: 388, dtype: float64
CRIM         8.15174
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.70000
RM           5.39000
AGE         98.90000
DIS          1.72810
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          396.90000
LSTAT       20.85000
Name: 389, dtype: float64
CRIM         6.96215
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.70000
RM           5.71300
AGE         97.00000
DIS          1.92650
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          394.43000
LSTAT       17.11000
Name: 390, dtype: float64
CRIM         5.29305
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.70000
RM           6.05100
AGE         82.50000
DIS          2.16780

Name: 393, dtype: float64
CRIM        13.3598
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6930
RM           5.8870
AGE         94.7000
DIS          1.7821
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       16.3500
Name: 394, dtype: float64
CRIM         8.71675
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.69300
RM           6.47100
AGE         98.80000
DIS          1.72570
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          391.98000
LSTAT       17.12000
Name: 395, dtype: float64
CRIM         5.87205
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.69300
RM           6.40500
AGE         96.00000
DIS          1.67680
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          396.90000
LSTAT       19.37000
Name: 396, dtype: float64
CRIM         7.67202
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.69300
RM           5.74700
AGE         98.90000
DIS          1.63340
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          393.10000
LSTAT       19.92000
Name: 397, dtype: float64
CRIM        38.3518
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6930
RM           5.4530
AGE        100.0000
DIS          1.4896
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       30.5900
Name: 398, dtype: float64
CRIM        25.0461
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6930
RM           5.9870
AGE        100.0000
DIS          1.5888
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       26.7700
Name: 400, dtype: float64
CRIM        14.2362
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6930
RM           6.3430
AGE        100.0000
DIS          1.5741
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       20.3200
Name: 401, dtype: float64
CRIM         9.59571
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.69300
RM           6.40400
AGE        100.00000
DIS          1.63900
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          376.11000
LSTAT       20.31000
Name: 402, dtype: float64
CRIM        24.8017
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6930
RM           5.3490
AGE         96.0000
DIS          1.7028
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       19.7700
Name: 403, dtype: float64
CRIM        67.9208
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6930
RM           5.6830
AGE        100.0000
DIS          1.4254
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          384.9700
LSTAT       22.9800
Name: 405, dtype: float64
CRIM        20.7162
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6590
RM           4.1380
AGE        100.0000
DIS          1.1781
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          370.2200
LSTAT       23.3400
Name: 406, dtype: float64
CRIM         9.39063
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.74000
RM           5.62700
AGE         93.90000
DIS          1.81720
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          396.90000
LSTAT       22.88000
Name: 439, dtype: float64
CRIM        22.0511
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7400
RM           5.8180
AGE         92.4000
DIS          1.8662
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          391.4500
LSTAT       22.1100
Name: 440, dtype: float64
CRIM         9.72418
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.74000
RM           6.40600
AGE         97.20000
DIS          2.06510
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          385.96000
LSTAT       19.52000
Name: 441, dtype: float64
CRIM         5.66637
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.74000
RM           6.21900
AGE        100.00000
DIS          2.00480
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          395.69000
LSTAT       16.59000
Name: 442, dtype: float64
CRIM         9.96654
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.74000
RM           6.48500
AGE        100.00000
DIS          1.97840
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          386.73000
LSTAT       18.85000
Name: 443, dtype: float64
CRIM         9.92485
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.74000
RM           6.25100
AGE         96.60000
DIS          2.19800
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          388.52000
LSTAT       16.44000
Name: 447, dtype: float64
CRIM         9.32909
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.18500
AGE         98.70000
DIS          2.26160
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          396.90000
LSTAT       18.13000
Name: 448, dtype: float64
CRIM         5.44114
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.65500
AGE         98.20000
DIS          2.35520
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          355.29000
LSTAT       17.73000
Name: 451, dtype: float64
CRIM         5.09017
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.29700
AGE         91.80000
DIS          2.36820
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          385.09000
LSTAT       17.27000
Name: 452, dtype: float64
CRIM         8.24809
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           7.39300
AGE         99.30000
DIS          2.45270
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          375.87000
LSTAT       16.74000
Name: 453, dtype: float64
CRIM         6.80117
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.08100
AGE         84.40000
DIS          2.71750
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          396.90000
LSTAT       14.70000
Name: 459, dtype: float64
CRIM         3.69311
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.37600
AGE         88.40000
DIS          2.56710
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          391.43000
LSTAT       14.65000
Name: 461, dtype: float64
CRIM         6.65492
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.31700
AGE         83.00000
DIS          2.73440
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          396.90000
LSTAT       13.99000
Name: 462, dtype: float64
CRIM         5.82115
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.51300
AGE         89.90000
DIS          2.80160
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          393.82000
LSTAT       10.29000
Name: 463, dtype: float64
CRIM         7.83932
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.65500
RM           6.20900
AGE         65.40000
DIS          2.96340
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          396.90000
LSTAT       13.22000
Name: 464, dtype: float64
CRIM        15.5757
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.5800
RM           5.9260
AGE         71.0000
DIS          2.9084
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          368.7400
LSTAT       18.1300
Name: 468, dtype: float64
CRIM        13.0751
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.5800
RM           5.7130
AGE         56.7000
DIS          2.8237
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          396.9000
LSTAT       14.7600
Name: 469, dtype: float64
CRIM         4.34879
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.58000
RM           6.16700
AGE         84.00000
DIS          3.03340
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          396.90000
LSTAT       16.29000
Name: 470, dtype: float64
CRIM         4.03841
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.53200
RM           6.22900
AGE         90.70000
DIS          3.09930
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          395.33000
LSTAT       12.87000
Name: 471, dtype: float64
CRIM         3.56868
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.58000
RM           6.43700
AGE         75.00000
DIS          2.89650
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          393.37000
LSTAT       14.36000
Name: 472, dtype: float64
CRIM         4.64689
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.61400
RM           6.98000
AGE         67.60000
DIS          2.53290
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          374.68000
LSTAT       11.66000
Name: 473, dtype: float64
CRIM         8.05579
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.58400
RM           5.42700
AGE         95.40000
DIS          2.42980
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          352.58000
LSTAT       18.14000
Name: 474, dtype: float64
CRIM         4.87141
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.61400
RM           6.48400
AGE         93.60000
DIS          2.30530
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          396.21000
LSTAT       18.68000
Name: 476, dtype: float64
CRIM        15.0234
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6140
RM           5.3040
AGE         97.3000
DIS          2.1007
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          349.4800
LSTAT       24.9100
Name: 477, dtype: float64
CRIM        10.2330
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6140
RM           6.1850
AGE         96.7000
DIS          2.1705
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          379.7000
LSTAT       18.0300
Name: 478, dtype: float64
CRIM        14.3337
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6140
RM           6.2290
AGE         88.0000
DIS          1.9512
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          383.3200
LSTAT       13.1100
Name: 479, dtype: float64
CRIM         5.82401
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.53200
RM           6.24200
AGE         64.70000
DIS          3.42420
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          396.90000
LSTAT       10.74000
Name: 480, dtype: float64
CRIM         5.70818
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.53200
RM           6.75000
AGE         74.90000
DIS          3.33170
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          393.07000
LSTAT        7.74000
Name: 481, dtype: float64
CRIM         5.73116
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.53200
RM           7.06100
AGE         77.00000
DIS          3.41060
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          395.28000
LSTAT        7.01000
Name: 482, dtype: float64
CRIM         2.81838
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.53200
RM           5.76200
AGE         40.30000
DIS          4.09830
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          392.92000
LSTAT       10.42000
Name: 483, dtype: float64
CRIM         2.37857
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.58300
RM           5.87100
AGE         41.90000
DIS          3.72400
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          370.73000
LSTAT       13.34000
Name: 484, dtype: float64
CRIM         3.67367
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.58300
RM           6.31200
AGE         51.90000
DIS          3.99170
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          388.62000
LSTAT       10.58000
Name: 485, dtype: float64
CRIM         5.69175
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.58300
RM           6.11400
AGE         79.80000
DIS          3.54590
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          392.68000
LSTAT       14.98000
Name: 486, dtype: float64
CRIM         4.83567
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.58300
RM           5.90500
AGE         53.20000
DIS          3.15230
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          388.22000
LSTAT       11.45000
Name: 487, dtype: float64
CRIM         0.15086
ZN           0.00000
INDUS       27.74000
CHAS         0.00000
NOX          0.60900
RM           5.45400
AGE         92.70000
DIS          1.82090
RAD          4.00000
TAX        711.00000
PTRATIO     20.10000
B          395.09000
LSTAT       18.06000
Name: 488, dtype: float64
CRIM         0.10574
ZN           0.00000
INDUS       27.74000
CHAS         0.00000
NOX          0.60900
RM           5.98300
AGE         98.80000
DIS          1.86810
RAD          4.00000
TAX        711.00000
PTRATIO     20.10000
B          390.11000
LSTAT       18.07000
Name: 491, dtype: float64
CRIM         0.11132
ZN           0.00000
INDUS       27.74000
CHAS         0.00000
NOX          0.60900
RM           5.98300
AGE         83.50000
DIS          2.10990
RAD          4.00000
TAX        711.00000
PTRATIO     20.10000
B          396.90000
LSTAT       13.35000
Name: 492, dtype: float64
Cluster  1
CRIM         3.69695
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71800
RM           4.96300
AGE         91.40000
DIS          1.75230
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          316.03000
LSTAT       14.00000
Name: 366, dtype: float64
CRIM        20.0849
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7000
RM           4.3680
AGE         91.2000
DIS          1.4395
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          285.8300
LSTAT       30.6300
Name: 384, dtype: float64
CRIM         9.91655
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.69300
RM           5.85200
AGE         77.80000
DIS          1.50040
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          338.16000
LSTAT       29.97000
Name: 399, dtype: float64
CRIM        41.5292
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6930
RM           5.5310
AGE         85.4000
DIS          1.6074
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          329.4600
LSTAT       27.3800
Name: 404, dtype: float64
CRIM        11.9511
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6590
RM           5.6080
AGE        100.0000
DIS          1.2852
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          332.0900
LSTAT       12.1300
Name: 407, dtype: float64
CRIM         7.40389
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.59700
RM           5.61700
AGE         97.90000
DIS          1.45470
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          314.64000
LSTAT       26.40000
Name: 408, dtype: float64
CRIM        14.4383
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.5970
RM           6.8520
AGE        100.0000
DIS          1.4655
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          179.3600
LSTAT       19.7800
Name: 409, dtype: float64
CRIM        28.6558
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.5970
RM           5.1550
AGE        100.0000
DIS          1.5894
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          210.9700
LSTAT       20.0800
Name: 413, dtype: float64
CRIM        11.0874
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7180
RM           6.4110
AGE        100.0000
DIS          1.8589
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          318.7500
LSTAT       15.0200
Name: 420, dtype: float64
CRIM         7.02259
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71800
RM           6.00600
AGE         95.30000
DIS          1.87460
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          319.98000
LSTAT       15.70000
Name: 421, dtype: float64
CRIM        12.0482
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6140
RM           5.6480
AGE         87.6000
DIS          1.9512
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          291.5500
LSTAT       14.1000
Name: 422, dtype: float64
CRIM        12.8023
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7400
RM           5.8540
AGE         96.6000
DIS          1.8956
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          240.5200
LSTAT       23.7900
Name: 444, dtype: float64
CRIM         6.28807
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.74000
RM           6.34100
AGE         96.40000
DIS          2.07200
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          318.01000
LSTAT       17.79000
Name: 446, dtype: float64

CRIM         7.52601
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.41700
AGE         98.30000
DIS          2.18500
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          304.21000
LSTAT       19.31000
Name: 449, dtype: float64
CRIM         7.75223
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.30100
AGE         83.70000
DIS          2.78310
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          272.21000
LSTAT       16.23000
Name: 458, dtype: float64
CRIM         4.81213
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.70100
AGE         90.00000
DIS          2.59750
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          255.23000
LSTAT       16.42000
Name: 460, dtype: float64
CRIM         3.1636
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6550
RM           5.7590
AGE         48.2000
DIS          3.0665
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          334.4000
LSTAT       14.1300
Name: 465, dtype: float64
CRIM         4.42228
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.58400
RM           6.00300
AGE         94.50000
DIS          2.54030
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          331.29000
LSTAT       21.32000
Name: 467, dtype: float64
CRIM         6.39312
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.58400
RM           6.16200
AGE         97.40000
DIS          2.20600
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          302.76000
LSTAT       24.10000
Name: 475, dtype: float64
CRIM         0.18337
ZN           0.00000
INDUS       27.74000
CHAS         0.00000
NOX          0.60900
RM           5.41400
AGE         98.30000
DIS          1.75540
RAD          4.00000
TAX        711.00000
PTRATIO     20.10000
B          344.05000
LSTAT       23.97000
Name: 489, dtype: float64
CRIM         0.20746
ZN           0.00000
INDUS       27.74000
CHAS         0.00000
NOX          0.60900
RM           5.09300
AGE         98.00000
DIS          1.82260
RAD          4.00000
TAX        711.00000
PTRATIO     20.10000
B          318.43000
LSTAT       29.68000
Name: 490, dtype: float64
Cluster  2
CRIM        13.5222
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6310
RM           3.8630
AGE        100.0000
DIS          1.5106
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          131.4200
LSTAT       13.3300
Name: 367, dtype: float64
CRIM        51.1358
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.5970
RM           5.7570
AGE        100.0000
DIS          1.4130
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B            2.6000
LSTAT       10.1100
Name: 410, dtype: float64
CRIM        14.0507
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.5970
RM           6.6570
AGE        100.0000
DIS          1.5275
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B           35.0500
LSTAT       21.2200
Name: 411, dtype: float64
CRIM        18.8110
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.5970
RM           4.6280
AGE        100.0000
DIS          1.5539
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B           28.7900
LSTAT       34.3700
Name: 412, dtype: float64
CRIM        45.7461
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6930
RM           4.5190
AGE        100.0000
DIS          1.6582
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B           88.2700
LSTAT       36.9800
Name: 414, dtype: float64
CRIM        18.0846
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6790
RM           6.4340
AGE        100.0000
DIS          1.8347
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B           27.2500
LSTAT       29.0500
Name: 415, dtype: float64
CRIM        10.8342
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6790
RM           6.7820
AGE         90.8000
DIS          1.8195
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B           21.5700
LSTAT       25.7900
Name: 416, dtype: float64
CRIM        25.9406
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6790
RM           5.3040
AGE         89.1000
DIS          1.6475
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          127.3600
LSTAT       26.6400
Name: 417, dtype: float64
CRIM        73.5341
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6790
RM           5.9570
AGE        100.0000
DIS          1.8026
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B           16.4500
LSTAT       20.6200
Name: 418, dtype: float64
CRIM        11.8123
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7180
RM           6.8240
AGE         76.5000
DIS          1.7940
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B           48.4500
LSTAT       22.7400
Name: 419, dtype: float64
CRIM         7.05042
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.61400
RM           6.10300
AGE         85.10000
DIS          2.02180
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B            2.52000
LSTAT       23.29000
Name: 423, dtype: float64
CRIM         8.79212
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.58400
RM           5.56500
AGE         70.60000
DIS          2.06350
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B            3.65000
LSTAT       17.16000
Name: 424, dtype: float64
CRIM        15.8603
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6790
RM           5.8960
AGE         95.4000
DIS          1.9096
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B            7.6800
LSTAT       24.3900
Name: 425, dtype: float64
CRIM        12.2472
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.5840
RM           5.8370
AGE         59.7000
DIS          1.9976
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B           24.6500
LSTAT       15.6900
Name: 426, dtype: float64
CRIM        37.6619
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.6790
RM           6.2020
AGE         78.7000
DIS          1.8629
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B           18.8200
LSTAT       14.5200
Name: 427, dtype: float64
CRIM         7.36711
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.67900
RM           6.19300
AGE         78.10000
DIS          1.93560
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B           96.73000
LSTAT       21.52000
Name: 428, dtype: float64
CRIM         9.33889
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.67900
RM           6.38000
AGE         95.60000
DIS          1.96820
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B           60.72000
LSTAT       24.08000
Name: 429, dtype: float64
CRIM         8.49213
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.58400
RM           6.34800
AGE         86.10000
DIS          2.05270
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B           83.45000
LSTAT       17.64000
Name: 430, dtype: float64
CRIM        10.0623
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.5840
RM           6.8330
AGE         94.3000
DIS          2.0882
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B           81.3300
LSTAT       19.6900
Name: 431, dtype: float64
CRIM         6.44405
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.58400
RM           6.42500
AGE         74.80000
DIS          2.20040
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B           97.95000
LSTAT       12.03000
Name: 432, dtype: float64
CRIM         5.58107
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.43600
AGE         87.90000
DIS          2.31580
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B          100.19000
LSTAT       16.22000
Name: 433, dtype: float64
CRIM        13.9134
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7130
RM           6.2080
AGE         95.0000
DIS          2.2222
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          100.6300
LSTAT       15.1700
Name: 434, dtype: float64
CRIM        11.1604
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7400
RM           6.6290
AGE         94.6000
DIS          2.1247
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B          109.8500
LSTAT       23.2700
Name: 435, dtype: float64
CRIM        14.4208
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7400
RM           6.4610
AGE         93.3000
DIS          2.0026
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B           27.4900
LSTAT       18.0500
Name: 436, dtype: float64
CRIM        15.1772
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7400
RM           6.1520
AGE        100.0000
DIS          1.9142
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B            9.3200
LSTAT       26.4500
Name: 437, dtype: float64
CRIM        13.6781
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7400
RM           5.9350
AGE         87.9000
DIS          1.8206
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B           68.9500
LSTAT       34.0200
Name: 438, dtype: float64
CRIM        10.6718
ZN           0.0000
INDUS       18.1000
CHAS         0.0000
NOX          0.7400
RM           6.4590
AGE         94.8000
DIS          1.9879
RAD         24.0000
TAX        666.0000
PTRATIO     20.2000
B           43.0600
LSTAT       23.9800
Name: 445, dtype: float64
CRIM         6.71772
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.74900
AGE         92.60000
DIS          2.32360
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B            0.32000
LSTAT       17.44000
Name: 450, dtype: float64
CRIM         9.51363
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.72800
AGE         94.10000
DIS          2.49610
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B            6.68000
LSTAT       18.71000
Name: 454, dtype: float64
CRIM         4.75237
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           6.52500
AGE         86.50000
DIS          2.43580
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B           50.92000
LSTAT       18.13000
Name: 455, dtype: float64
CRIM         4.66883
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           5.97600
AGE         87.90000
DIS          2.58060
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B           10.48000
LSTAT       19.01000
Name: 456, dtype: float64
CRIM         8.20058
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.71300
RM           5.93600
AGE         80.30000
DIS          2.77920
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B            3.50000
LSTAT       16.94000
Name: 457, dtype: float64
CRIM         3.77498
ZN           0.00000
INDUS       18.10000
CHAS         0.00000
NOX          0.65500
RM           5.95200
AGE         84.70000
DIS          2.87150
RAD         24.00000
TAX        666.00000
PTRATIO     20.20000
B           22.01000
LSTAT       17.15000
Name: 466, dtype: float64

In [96]:
clusters[0][1].index

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT'],
      dtype='object')

In [94]:
df2=pd.DataFrame()
for i in range(len(clusters.keys())):
    df2[f'{i}']= [clusters[i]]

In [95]:
df2

,0,1,2,3,4,5,6,7,8
0,"[[0.00632, 18.0, 2.31, 0.0, 0.538, 6.575, 65.2...","[[3.69695, 0.0, 18.1, 0.0, 0.718, 4.963, 91.4,...","[[13.5222, 0.0, 18.1, 0.0, 0.631, 3.863, 100.0...","[[0.0136, 75.0, 4.0, 0.0, 0.41, 5.888, 47.6, 7...","[[8.98296, 0.0, 18.1, 1.0, 0.77, 6.212, 97.4, ...","[[0.02731, 0.0, 7.07, 0.0, 0.469, 6.421, 78.9,...","[[1.38799, 0.0, 8.14, 0.0, 0.538, 5.95, 82.0, ...","[[0.02055, 85.0, 0.74, 0.0, 0.41, 6.383, 35.7,...","[[0.027630000000000002, 75.0, 2.95, 0.0, 0.428..."